### ISSUE TITLE
CUDA miner does not support RTX 20 series video cards

### ISSUE THREAD

**Issue by CikeQiu** [aeternity/aeternity#1888]
## Expected Behavior

Mining.

## Actual Behavior

Can't mine any blocks.

## Steps to Reproduce the Problem

  1. Config node and miners.
  2. Use GTX 1080 Ti, can mine blocks.
  3. Use RTX 2080 Ti, get too many '2-cycle found' in cuckoo.log, and can not mine any blocks.
  
  
## Logs, error output, etc.
 
 (`epoch.yaml` configuration file, `log/epoch.log` log file plus other related logs, e.g., `log/epoch_sync.log`, `log/epoch_mining.log`; if it’s long, please paste to https://ghostbin.com/ and insert the link here)
 

![971543892746_ pic_hd](https://user-images.githubusercontent.com/29170705/49416330-932a5880-f7b4-11e8-91ef-b8a472221fbe.jpg)

## Specifications

  - Virtualization: [*none*]
  - Hardware specs: 
    * RAM: 32 GB
    * CPU: Intel i7-8700K
  - OS: [*Ubuntu, 18.04*]
  - Node Version: 1.0.0-rc6, Roma release

**Comment by kryztoval** [comment]
since you clearly have both cards, can you try the same executable with the same parameter on both cards ? you should be seeing the same result in both

**Comment by CikeQiu** [comment]
Actually I have done this before, and the result is 1080Ti can mine blocks, and 2080Ti get '2-cycle found's

**Comment by CikeQiu** [comment]
And if I use cuda30 which built in 1.0.0-rc2, and change cuda29 to cuda30 in epoch.yaml, then start 1.0.0-rc6 node, I can see blocks are mined.
But cannot work for Roma, not be able to sync blocks, the log is "incorrect-pow".

Sorry about my english if you don't get me.

**Comment by droidzhangy** [comment]
HI, i checked the 1.0.0-rc2 version and Roma version, the aeternity/cuckoo git commit() used in these two version are same(both of them built cuda20 rather than cuda30), you can find them in apps/aecuckoo/Makefile.

So i could not understand the problem you pointed out...

**Comment by droidzhangy** [comment]
REPO = https://github.com/aeternity/cuckoo.git
COMMIT = a66b88ab8514b7232b1e148a4760f9258d5457f0

**Comment by CikeQiu** [comment]
I think you guys can find something different between them, there are too many '2-cycle found', may cause https://ghostbin.com/ to crash, the web just show me 'Internal Server Error'.

**Comment by droidzhangy** [comment]
I‘m a aeternity fan too... And i also plan to mine ae with RTX 20 series......
But there is a good news, tromp said that he has fixed the cuckoo bug with RTX 20XX,
https://github.com/tromp/cuckoo/commits/master

We hoped that AE dev team sync these upstream commits asap...

**Comment by CikeQiu** [comment]
> I‘m a aeternity fan too... And i also plan to mine ae with RTX 20 series......
> But there is a good news, tromp said that he has fixed the cuckoo bug with RTX 20XX,
> https://github.com/tromp/cuckoo/commits/master
> 
> We hoped that AE dev team sync these upstream commits asap...

Good job!

**Comment by tolbrino** [comment]
We are in the process of merging these changes. It does take some time since we are also improving the general way GPU mining is handled to improve efficiency.

**Comment by CikeQiu** [comment]
Will you fix this in next release?

**Comment by tolbrino** [comment]
There is a good chance that we can finish this in time to be included in the next release.

**Comment by tolbrino** [comment]
@CikeQiu You could test the WIP: https://forum.aeternity.com/t/improved-mining-speed-multi-gpu/1753

**Comment by CikeQiu** [comment]
sorry for the late reply, I will do some tests on this weekend.
