### ISSUE TITLE
Can not get pub-key 

### ISSUE THREAD

**Issue by prettyCoders** [aeternity/aeternity#1971]
The AE node is running by docker
Below are The command:
docker pull aeternity/epoch
docker run -p 3013:3013 -p 3015:3015 aeternity/epoch

Now,I want to get my pub-key use command like this:curl http://127.0.0.1:3013/v2/account/pub-key,
But the sever did not return anything!
image:
![image](https://user-images.githubusercontent.com/36216120/50333529-a1ac9a00-0540-11e9-9b0a-0181f65c693e.png)

**Comment by hanssv** [comment]
Why do you expect that to return anything? The node does not have an account, and that API has been gone for a couple of months? 

Do we have some old documentation pointing to it perhaps?

**Comment by prettyCoders** [comment]
How do i create account except  Base æpp?

**Comment by prettyCoders** [comment]
![qq 20181224095009](https://user-images.githubusercontent.com/36216120/50389181-dfd4d400-0761-11e9-9bae-eb9757ca57be.png)

**Comment by prettyCoders** [comment]
Why did you say that can`t create account by node?

**Comment by evdoks** [comment]
It is described [here] (https://github.com/aeternity/epoch/blob/master/docs/configuration.md#beneficiary-account). You can also use (AEternity CLI)[https://github.com/aeternity/aepp-cli-js] - command line interface.
