### ISSUE TITLE
Is there any API to get block(block must contain transaction info) by height?

### ISSUE THREAD

**Issue by prettyCoders** [aeternity/aeternity#1983]
like this:
![image](https://user-images.githubusercontent.com/36216120/50508088-543da900-0abb-11e9-983f-f50ded3bcd32.png)
![image](https://user-images.githubusercontent.com/36216120/50508096-5acc2080-0abb-11e9-9308-447dee9ddaee.png)

**Comment by evdoks** [comment]
There is an 'internal' API that is running on port 3013 by default. See Swagger schema of the API [here](http://aeternity.com/epoch-api-docs/?config=https://raw.githubusercontent.com/aeternity/epoch/master/apps/aehttp/priv/swagger.json#/chain).

**Comment by mintymac** [comment]
@evdoks Thank you for that information.  [raw](https://raw.githubusercontent.com/aeternity/epoch/master/apps/aehttp/priv/swagger.json#/chain) - Docs server down.

**Comment by dincho** [comment]
Docs URL has been updated, try [the new link](
http://aeternity.com/api-docs/?config=https://raw.githubusercontent.com/aeternity/epoch/master/apps/aehttp/priv/swagger.json#/chai)
