### ISSUE TITLE
Systemd and other startup scripts

### ISSUE THREAD

**Issue by sammy007** [aeternity/aeternity#2166]
Kinda expected to be provided in some misc directory.

**Comment by tolbrino** [comment]
Feel free to provide a PR.

**Comment by dincho** [comment]
We're actually looking into it, but it's kinda useless until we have distro packages, which is in progress.

In the meantime you can use this [Ansible/Jinja template](https://github.com/aeternity/infrastructure/blob/master/ansible/templates/aeternity.service.j2) as reference.

**Comment by tolbrino** [comment]
Closing since @dincho has provided an example.
