### ISSUE TITLE
Very slow sync

### ISSUE THREAD

**Issue by sammy007** [aeternity/aeternity#2167]
Took 10 minutes to sync ~3,000 blocks. Assuming whole chain is pretty much empty it's reasonable to expect fast sync.

v1.4.0, running on bare metal server in DC.

Update: 2.2h to sync 20251 blocks. This is a joke.

**Comment by hanssv** [comment]
That sounds a bit slow, yes. The upcoming 2.0 release candidate has some improvements in this area, and we are going to look further into speeding up block insertion (most of the time in sync is spent inserting blocks, you need a very bad internet connection for it to be bounded by the network).

**Comment by sammy007** [comment]
The size of first 20K blocks is less than 1 GB of data. Does not fit into category `a bit slow` at all, it looks like some dirty prototype code went to production.

**Comment by hanssv** [comment]
Did some measurements (in preparation for making it faster) last Friday. The whole chain synced in less than an hour on my laptop on a not overly fast office internet in northern Europe... 

So there is probably something more going on here...

**Comment by sammy007** [comment]
Still here. Can't finish sync for a day already, latest release on 8 core Atom amd64 in DC with fast link.

**Comment by jur0** [comment]
Today we experienced an issue with the sync on `ae_uat`. AWS Linux instance was running the node in a docker container and the sync got stuck at height 47956 when ~30% of the chain was synced. The `aeternity_sync.log` had a bunch of timeout messages when the node tried to connect to the other peers. `ulimit -n` on the Linux host showed 1024 (soft limit) and `ulimit -Hn` (hard limit) was 4096. `ulimit -n` in docker returned 133586 (which according to [this](https://stackoverflow.com/questions/46211558/ulimits-in-docker-host-vs-container) should match the hard limit on the host).

After increasing both soft and hard limits to [this value](https://github.com/aeternity/aeternity/blob/master/hooks/pre_start.sh#L3) on the host and restarting the docker, the sync started to work again. Although, it took some time (~1-2 min) after the restart, so it's not clear whether setting the limits or restarting the node made it work again.

**Comment by tolbrino** [comment]
Closing since the issue is stale and various improvements are being addressed in the linked issues.
