### ISSUE TITLE
What's keys -> dir and keys -> peer_password mean in aeternity.yaml

### ISSUE THREAD

**Issue by crcrcr999** [aeternity/aeternity#2199]
I don't know.What's keys -> dir and keys -> peer_password mean in aeternity.yaml?I create many account by aecli,but with different password,should I use my account's password for peer_password?

**Comment by dincho** [comment]
This is the Noise protocol peer keys directory and password used to encrypt the keys.
You don't have to (and should not) use your account password.

Usually you don't have to do anything with it (keep the defaults) to join and use the networks. It need a special care (e.g. backup the keys and password) if you want to keep your Noise keypair permanent.

**Comment by evdoks** [comment]
Closing as answered
