### ISSUE TITLE
The transaction is not broadcast?

### ISSUE THREAD

**Issue by shawn0322** [aeternity/aeternity#2210]
I signed a transaction：tx_+KkLAfhCuEAKogQVtxVxbzG2pnIYG/dl0tHMs3KKZU2Gy0HnNM9aYkdgjwHco+4Y455TiCoxhAMcWIQb1L7e46u+daDYyt4PuGH4XwwBoQERH+u7xflJFzGvHnT3XZX2YfXWW7Y6V+ckCUtBclgDEKEBYTPsOCht120pZK8Pz0BsEl75AEQ16vc8zOT5ZX7Psv+IAWNFeF2KAACCdTCCrgQBiHdvcmtzID0pdawpDg==
When I used the “/transactions” broadcast transaction, I got tx_hash.
th_2Gn7YpWtKq3JQt8cEiRB7jdwrUJ4V4aj2v6nGXfUZKEnsf4Aoq

 But the transaction was not found on the browser.
![image](https://user-images.githubusercontent.com/38547567/53587189-b5b9eb00-3bc4-11e9-8400-f992b462cf4d.png)
It seems that the transaction is only on my node.
![image](https://user-images.githubusercontent.com/38547567/53587319-003b6780-3bc5-11e9-8e7b-fe38bdc9216c.png)

What problem have I encountered? How can I set up my node?

Very anxious, I hope to get help

**Comment by marc0olo** [comment]
are you sure that the transaction was submitted to the chain? from the structure itself it seems to be valid. you can check the validity for (mainnet) transactions with this tool:
- https://goggles.aepps.com/

when I put in your signed transaction I get the following output:
![image](https://user-images.githubusercontent.com/8124114/53602652-b5632500-3baf-11e9-9746-208e72483b3e.png)

two things to be discovered:
- amount of fee is to low
   - probably the tool is already calculating with the fee-structure of the new `Minerva release`
- the ttl is expired now

so personally I guess you haven't submitted the signed tx to the network

**Comment by shawn0322** [comment]
谢谢。Thank you for solving my problem. @marc0olo
