### ISSUE TITLE
OracleRespondTx  Vs  OracleResponseTx

### ISSUE THREAD

**Issue by shekhar-shubhendu** [aeternity/aeternity#2564]
## Expected Behavior

The transaction type should be `OracleRespondTx `

## Actual Behavior

The transaction type is `OracleResponseTx `

## Steps to Reproduce the Problem

transaction link: https://sdk-mainnet.aepps.com/v2/transactions/th_apTWfWu6RPLyritqib2mnKWc5Hcaw6uVkQC68jKfUq2t2mStS

## Related Links

swagger api: https://sdk-mainnet.aepps.com/api

protocol: https://github.com/aeternity/protocol/search?q=OracleRespondTx&unscoped_q=OracleRespondTx

**Comment by shekhar-shubhendu** [comment]
@lucafavatella will this be part of the upcoming node release?

**Comment by lucafavatella** [comment]
> @lucafavatella will this be part of the upcoming node release?

@shekhar-shubhendu It is under review so I cannot promise, but hopefully yes.
