### ISSUE TITLE
I run the aestratum_client,but get error in this place

### ISSUE THREAD

**Issue by xzxuzhou112** [aeternity/aeternity#2573]
## Expected Behavior
Starting of aestratum client

## Actual Behavior
After executing the./rabar3 shell, it appears those error

## Steps to Reproduce the Problem

  1.==> Booted enacl
===> Booted aecuckoo
===> Booted aecuckooprebuilt
===> Booted aeminer
18:44:09.778 [error] Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<“47.244.15.72”>>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => …,…},…}) at <0.350.0> exit with reason normal in context child_terminated

 2.===> Booted aestratum_lib
18:44:09.778 [info] Application aestratum_client started on node nonode@nohost
 
 3.===> Booted aestratum_client
18:44:09.868 [error] Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<“47.244.15.72”>>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => …,…},…}) at <0.357.0> exit with reason normal in context child_terminated
18:44:09.868 [error] Supervisor aestratum_client_sup had child aestratum_client_handler started with aestratum_client_handler:start_link(#{conn_cfg => #{host => <<“47.244.15.72”>>,port => 8888,req_retries => 3,req_timeout => 14000,socket_opts => …,…},…}) at <0.357.0> exit with reason reached_max_restart_intensity in context shutdown
18:44:09.869 [info] Application aestratum_client exited with reason: shutdown

## Logs, error output, etc.

*`aeternity.yaml` configuration file (formerly named `epoch.yaml`)*

*`log/aeternity.log` log file (formerly named `log/epoch.log`) - plus other related logs, e.g., `log/aeternity_sync.log` (formerly named `log/epoch_sync.log`), `log/aeternity_mining.log` (formerly named `log/epoch_mining.log`); if it’s long, please paste to https://ghostbin.com/ and insert the link here.*

https://github.com/xzxuzhou112/error-log-for-aestratum

## Specifications

  - Virtualization: none [*none / metal / container / VM*]
  - Hardware specs for client:
    * RAM:4G
    * CPU: i3-4130
  - OS:Ubuntu 18.04 LTS [*distribution, version*]
  - Node Version:none

  - Hardware specs for server:
    * RAM:4G
    * CPU: 2vcpu
  - OS:Ubuntu 18.04 LTS [*distribution, version*]
  - Node Version:3.3.0

**Comment by skkw** [comment]
This ticket is for tracking of the following discussion: https://forum.aeternity.com/t/i-run-the-aestratum-client-but-get-error-in-this-place/4048/21
