### ISSUE TITLE
interface document

### ISSUE THREAD

**Issue by simpleshark** [aeternity/aeternity#2733]
## Expected Behavior

...
Hello!I want to connect my wallet and ask where I can find the interface document, such as generating address, transferring money, querying transaction records...
## Actual Behavior

...

## Steps to Reproduce the Problem

  1. ...
  1. ...
  1. ...

## Logs, error output, etc.

*`aeternity.yaml` configuration file (formerly named `epoch.yaml`)*

*`log/aeternity.log` log file (formerly named `log/epoch.log`) - plus other related logs, e.g., `log/aeternity_sync.log` (formerly named `log/epoch_sync.log`), `log/aeternity_mining.log` (formerly named `log/epoch_mining.log`); if it’s long, please paste to https://ghostbin.com/ and insert the link here.*

...

## Specifications

  - Virtualization: [*none / metal / container / VM*]
  - Hardware specs:
    * RAM:
    * CPU:
  - OS: [*distribution, version*]
  - Node Version:

**Comment by tolbrino** [comment]
Your description is vague. Maybe the information on the following sites help you out?

https://api-docs.aeternity.io/
http://aeternity.com/documentation-hub/

**Comment by evdoks** [comment]
Closing as stale
