### ISSUE TITLE
an issue abount aeternity deposit

### ISSUE THREAD

**Issue by past2017** [aeternity/aeternity#2756]
## Expected Behavior

there is should a tag to  differentiate AE and AE token

## Actual Behavior

there is not a tag to  differentiate AE and AE token

## Steps to Reproduce the Problem
1.   by  v2/transactions/{hash}
2.   get a transaction info
![image](https://user-images.githubusercontent.com/25541244/64470862-5db7fe80-d17c-11e9-8c8f-3280a1291666.png)
3. there is only recipient_id and type to confirm a deposit, so if there is an ae token, how to differentiate it?

## Specifications

  - Virtualization: [*none / metal / container / VM*]
  - Hardware specs:
    * RAM: 16G
    * CPU: 8 core
  - OS: [*distribution, version*]  ubunt16.04
  - Node Version:   4.2.1

**Comment by evdoks** [comment]
Could you please clarify, what do you exactly mean by "AE"?

**Comment by past2017** [comment]
> Could you please clarify, what do you exactly mean by "AE"?

aeternity

**Comment by evdoks** [comment]
Closed as stale
