### ISSUE TITLE
SC: channel_id not available in reestablish info message

### ISSUE THREAD

**Issue by AleksandarFilipov** [aeternity/aeternity#2854]
I would like to get the channel back on reestablish. Remainder: channel_id is required for performing reestablish. 

https://github.com/aeternity/protocol/blob/master/node/api/examples/channels/json-rpc/sc_ws_leave_reestablish.md#responder-----node-15

```
{
  "jsonrpc": "2.0",
  "method": "channels.info",
  "params": {
    "channel_id": null,
    "data": {
      "event": "channel_reestablished"
    }
  },
  "version": 1
}
```

Channel id is available on the next message which contains `"event" : open` but it's still confusing

**Comment by AleksandarFilipov** [comment]
for reconnect there is not message back at all. Guess this actually is a part of the harmonization reconnect/reestablish

**Comment by tolbrino** [comment]
> for reconnect there is not message back at all. Guess this actually is a part of the harmonization reconnect/reestablish
> 
> Peer left message is also missing, depending on how other end disconnected.

Please create separate issues for this.
