### ISSUE TITLE
Trigger CI on PRs from forks

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#2856]
## Expected Behavior

CI should trigger by fork PRs as well

## Actual Behavior

CI pipeline does not trigger

## Steps to Reproduce the Problem

1. Fork the aeternity repo
2. Create PR from your fork

## Logs, error output, etc.

Example PR https://github.com/aeternity/epoch/pull/1328

## Specifications

n/a

Note that as secrets cannot be shared with external contributors, jobs that require secrets should not trigger for such PRs.

Details:
- https://circleci.com/blog/managing-secrets-when-you-have-pull-requests-from-outside-contributors/
- https://circleci.com/blog/state-management-for-flutter-apps-with-mobx/

**Comment by tolbrino** [comment]
👍 This would be awesome.
