### ISSUE TITLE
CT: aesc_fsm_SUITE ==> all_tests.throughput.many_chs_msg_loop, timeout

### ISSUE THREAD

**Issue by velzevur** [aeternity/aeternity#2870]
## Expected Behavior

tests passing

## Actual Behavior
```
%%% aesc_fsm_SUITE ==> all_tests.throughput.many_chs_msg_loop: FAILED
%%% aesc_fsm_SUITE ==> {'EXIT',timeout}
```
[CI log](https://circleci.com/gh/aeternity/aeternity/88483)

**Comment by tolbrino** [comment]
@velzevur I thought this would have been fixed via https://github.com/aeternity/aeternity/issues/2835 but apparently not. I couldn't reproduce it locally though.

**Comment by velzevur** [comment]
I managed reproducing it by bumping the amount of channels. It should be fixed now. Closing
