### ISSUE TITLE
SC: aesc_fsm_SUITE ==> all_tests.round_too_high.check_incorrect_update: FAILED

### ISSUE THREAD

**Issue by tolbrino** [aeternity/aeternity#2915]
## Expected Behavior

Passing tests.

## Actual Behavior

Failing testcase.

```
aesc_fsm_SUITE ==> all_tests.round_too_high.check_incorrect_update: FAILED
```

## Steps to Reproduce the Problem

not known atm

## Logs, error output, etc.

https://circleci.com/gh/aeternity/aeternity/92138

**Comment by velzevur** [comment]
This happened because of [flush](https://github.com/aeternity/aeternity/blob/e561953210c14a2bde7664abfd9b794d8ab6475a/apps/aecore/test/aecore_suite_utils.erl#L443) in tests. This is fixed in master already
