### ISSUE TITLE
SC: Aborting operations expects aborted_updated but receives channel_conflict

### ISSUE THREAD

**Issue by AleksandarFilipov** [aeternity/aeternity#3004]
## Expected Behavior

Test pass

## Actual Behavior

:initiator expected {:channels_info, 0, :transient, **"aborted_update"**} received {:channels_update, 2, :self, **"channels.conflict"**}

inconsistent result. Always passes localy, and always fails on Circle CI

## Steps to Reproduce the Problem

Testcase is aviliable here: https://github.com/aeternity/ae-channel-service/blob/reproduce_abort/apps/ae_socket_connector/test/ae_socket_connector_test.exs#L134-L191

## Logs, error output, etc.

Circle CI test result can be found here: https://circleci.com/gh/aeternity/ae-channel-service/tree/reproduce_abort

Related https://github.com/aeternity/aeternity/issues/2962

**Comment by velzevur** [comment]
This actally seems fine. My analysis:
What [the test](https://github.com/aeternity/ae-channel-service/blob/reproduce_abort/apps/ae_socket_connector/test/ae_socket_connector_test.exs#L134-L191) does is that the `initiator` triggers an off-chain update (transfer of 5 tokens) and the `responder` rejects it.

According to [the docs](https://github.com/aeternity/protocol/blob/master/node/api/channels_api_usage.md#abort-update) this seems fine, namely the `responder` shall receive is:
```
{ 
   "jsonrpc":"2.0",
   "method":"channels.info",
   "params":{ 
      "channel_id":"ch_95Ya...",
      "data":{ 
         "event":"aborted_update"
      }
   },
   "version":1
}
```

Note the information important to the `initiator` in this case is in
```
If the other party had triggered the aborted update, it is informed with receiving the following message:

{
  "jsonrpc": "2.0",
  "method": "channels.conflict",
  "params": {
    "channel_id":"ch_95Ya...",
    "data": {
      "channel_id":"ch_95Ya...",
      "error_code": 147,
      "error_msg": "user-defined",
      "round": 5
    }
  },
  "version": 1
}
```

This seems fine to me, code is behaving according to documentation. This wasn't so some time ago so the bug might be basing locally on an old node version.

**Comment by AleksandarFilipov** [comment]
This used to be intermittent, restesting show that test passes as expected. https://github.com/aeternity/ae-channel-service/pull/49 closing issue
