### ISSUE TITLE
Retire Python UAT suite

### ISSUE THREAD

**Issue by tolbrino** [aeternity/aeternity#3009]
~~Currently python2.7 is used, which will be EOL in early 2020. Thus, we should update to the latest LTS version of python.~~

~~This requires changes in the CI configuration as well and must be tested on all platforms.~~

The Python UAT suite shall be retired. The tests need to be inspected for cases which are not handled by the systems tests yet. Such cases shall be ported to the system tests.

Some tests covered by the Python UAT shall be handled outside of the new UAT, see #3065 and https://github.com/aeternity/aeminer/issues/17

**Comment by ThomasArts** [comment]
The phyton tests do contribute very little to the tests we already have in aehttp_suite and some other places. It probably would be worth a day or two to read each test and see whether the same thing is tested elsewhere. Possibly we end up by only a handful of tests that are still worth porting... and probably porting to something else than python.

The python tests have one advantage, viz. that people not knowing Erlang see how the interface works. But, the question is whether this is still an advantage with all the SDKs we have at the moment. Users can look in a python SDK, a Go SDK or any other language of their taste to see how the interface works.

**Comment by sennui** [comment]
There were two original ideas around python tests.

1. The first, was to re-use json objects that are used in the test to build documentation with tutorials. Having tests would make them always up to date. 

2. The second, was to have non-erlang implemetation of API usage. It's supposedly easier to read then erlang. Potentially it would also caught bugs with serialization. 

I think none of the original reasons is valid now. For api doc we use swagger. For non-erlang approach we have SDKs. I am fine with removing python test framework.

**Comment by tolbrino** [comment]
I agree, the SDKs give a good idea already of how to use the API in the various languages. Porting the python tests to the system test suite makes sense as it reduces the complexity of the test setups.

The python UAT is in a weird state at the moment, since it was intended to become a lot more but @lucafavatella couldn't finish that vision.

**Comment by evdoks** [comment]
Any ideas on who start working on this task? Do we have volunteers?  Maybe @skkw, once he is done with GC.

**Comment by evdoks** [comment]
As discussed, let's follow @ThomasArts proposal by checking if there are tests worth porting and retire python UAT.

**Comment by ThomasArts** [comment]
Some preliminary cover statistics:

```
Only in "uats": [{{aec_peers,299},unique,8},
                 {{aec_peers,544},unique,1},
                 {{aec_peers,1078},unique,1},
                 {{aec_peers,1081},unique,1},
                 {{aec_peers,1190},unique,1},
                 {{aec_mining,149},unique,200},
                 {{aetx,495},unique,55},
                 {{aestratum_appsup,17},unique,16},
                 {{aemon_app,17},unique,16},
                 {{aemon_app,20},unique,16},
                 {{aec_peers_pool,993},unique,1},
                 {{aec_peers_pool,1146},unique,1},
                 {{aec_peers_pool,1281},unique,10},
                 {{aec_peers_pool,1495},unique,5},
                 {{aec_eper_metrics_probe,77},unique,470},
                 {{aec_eper_metrics_probe,78},unique,470},
                 {{aec_eper_metrics_probe,90},unique,470},
                 {{aec_eper_metrics_probe,93},unique,470},
                 {{aec_eper_metrics_probe,94},unique,470},
                 {{aec_eper_metrics_probe,98},unique,470},
                 {{aec_eper_metrics_probe,121},unique,470},
                 {{aec_eper_metrics_probe,122},unique,470},
                 {{aec_eper_metrics_probe,124},unique,1802},
                 {{aec_eper_metrics_probe,125},unique,1724},
                 {{aec_eper_metrics_probe,127},unique,78},
                 {{aec_eper_metrics_probe,132},unique,858},
                 {{aec_eper_metrics_probe,134},unique,78},
                 {{aec_eper_metrics_probe,136},unique,2106},
                 {{aec_eper_metrics_probe,137},unique,1248},
                 {{aec_eper_metrics_probe,139},unique,858},
                 {{aehttp_api_handler,59},unique,18},
                 {{aehttp_api_handler,65},unique,18},
                 {{aec_hard_forks,136},unique,549},
                 {{aec_hard_forks,138},unique,549},
                 {{aehttp_app,93},unique,16},
                 {{aehttp_app,94},unique,16}]
```
So there is not a whole lot more that is tested in uat tests. Looking into this more carefully now.

**Comment by ThomasArts** [comment]
aehttp_api_handler differences fixed via: https://github.com/aeternity/aeternity/commit/24d7c61e45a5332607686277766910c61dc34895

**Comment by ThomasArts** [comment]
In Python tests we **validate Swagger** file. Need to verify whether we can do enough validation on Erlang side to mimic that.

**Comment by ThomasArts** [comment]
> In Python tests we **validate Swagger** file. Need to verify whether we can do enough validation on Erlang side to mimic that.

Added a test to validate swagger as part of Erlang common test cycle.
https://github.com/aeternity/aeternity/pull/3044/commits/f354f453bd559f93a79efed6f07121cc2adb7f8e
