### ISSUE TITLE
Upgrade swagger API definition to OpenAPI 3

### ISSUE THREAD

**Issue by tolbrino** [aeternity/aeternity#3013]
The [current definition](https://github.com/aeternity/aeternity/blob/master/apps/aehttp/priv/swagger.yaml) uses [OpenAPI 2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md). [OpenAPI 3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md) provides [interesting features](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) which could further help to improve the API definition and thus client generation.

**Comment by dincho** [comment]
I already looked into this, the only issue is the library (dynamic API client) used in the "UAT"/python tests, so it has to be decided if we're going to drop them in https://github.com/aeternity/aeternity/issues/3009

IMO having a generated client is a step back

**Comment by evdoks** [comment]
@dincho we talked several times about dropping UAT and so far the consensus was that we should, probably, do this.

But could you, clarify on `having a generated client is a step back`?

**Comment by dincho** [comment]
> But could you, clarify on `having a generated client is a step back`?

Sure, having an additional step that based on the specification + a command -> generates a source code of the API client. This has been proven in the past that's additional hassle to support and adds a lot of noise in the SCM.

**Comment by uwiger** [comment]
I consider this issue done. A new issue could be created when it's time to retire the old swagger spec.
