### ISSUE TITLE
Oracle FATE queries need encoding like AEVM queries 

### ISSUE THREAD

**Issue by ThomasArts** [aeternity/aeternity#3021]
Oracle queries and responses are send as binaries encoded in a certain way. At the moment FATE queries are just arbitrary binaries, whereas AEVM binaries are encoded as contract bytecode.

```
  EncFormat = fun(F) -> if ABIVersion == ?ABI_AEVM_SOPHIA_1 ->
                                 aeser_api_encoder:encode(contract_bytearray, F);
                             true ->
                                 F
                          end end,
```
https://github.com/aeternity/aeternity/blob/082a7d47a9f71e90cfaca9ee934cc9cca73b2762/apps/aeoracle/src/aeo_oracles.erl#L176

The FATE ABI version is different and an encoding is needed.

**Comment by hanssv** [comment]
This does not break consensus it is just the serialization for JSON/HTTP, it will slightly change an API, that is all.
