### ISSUE TITLE
SC: state channels password is missing documentation

### ISSUE THREAD

**Issue by AleksandarFilipov** [aeternity/aeternity#3026]
## Expected Behavior

Describe `fsm_id` and `existing_fsm_id`. Remove reconnect documentation.

## Actual Behavior

Remove https://github.com/aeternity/protocol/blob/master/node/api/channels_api_usage.md#client-reconnect

...

## References

https://github.com/aeternity/aeternity/blob/master/docs/release-notes/next/GH-2822-session-token-encryption.md
https://github.com/aeternity/aeternity/pull/2911

**Comment by AleksandarFilipov** [comment]
Issue covered by this

https://github.com/aeternity/protocol/pull/444

**Comment by uwiger** [comment]
Solved e.g. as part of PR #470
