### ISSUE TITLE
SC: reestablish "fsm_up" comes with channel id == null

### ISSUE THREAD

**Issue by AleksandarFilipov** [aeternity/aeternity#3027]
## Expected Behavior

channel_id should be populated when fsm_up event is triggered

## Actual Behavior

channel_id is null

## Steps to Reproduce the Problem

Coming soon.

**Comment by uwiger** [comment]
The main issue here is that the `fsm_up` event is generated right after initial state has been created and the next state is determined. In the `Initiator`, this would mean that the `channel_open` message has been sent, and the FSM knows the temporary channel id, but the `Responder` still doesn't, in the corresponding position. The `Responder` needs to wait for receipt of the `channel_open` message to know the temporary channel id (generated by the `Initiator`).

**Comment by AleksandarFilipov** [comment]
Let's revisit this topic, client need to have a firm point where it knows it has enough information to perform a reestablish.

**Comment by uwiger** [comment]
Addressed in #3224
