### ISSUE TITLE
website  crashout，and return 522

### ISSUE THREAD

**Issue by csunny** [aeternity/aeternity#3055]
## Expected Behavior
When I visite the website http://www.aeternity.com/ ，  a error code 522 return.   

![image](https://user-images.githubusercontent.com/17919400/70043147-f7b40980-15fa-11ea-980f-915cc66f5b04.png)

Can someone fix this?

**Comment by evdoks** [comment]
Thank you for noticing it. We forwarded your report to the web site maintainers.

For the future reports, please note, that this GitHub project is dedicated exclusively to the development of aeternity node. Please, use the [forum](http://forum.aeternity.com) for reporting such issues in the future.
