### ISSUE TITLE
Add metrics to improve visibility of network state

### ISSUE THREAD

**Issue by tolbrino** [aeternity/aeternity#3070]
- Current difficulty
- Block propagation time
- Inter-block time
- fix the non-working micro-forks metric

Follow-up #3079

**Comment by ThomasArts** [comment]
Current difficulty is, as far as I can see, directly available from endpoint v2/status.

Tx round-trip time has been discussed in chat and can mean 2 things:
1) Time from posting a transaction to receiving it via gossip
2) Confirmation time: time from posting to being included in a micro-block.

Number 1) is tricky. If you post a transaction and get it returned, you could get it returned from your neighbouring node. There is no guarantee that more than you and your neighbour actually have received the Tx... We have no hop-count in gossip messages.

Number 2 is almost in place. We post monitoring transactions that contain a timestamp in the payload. I believe that for example account: ak_zvU8YQLagjcfng7Tg8yCdiZ1rpiWNp1PBn3vtUs44utSvbJVR is ours and has posted a payload looking like:
```183982:kh_JwhH8QCTtJyoLZ4Zo6DtkVfXUPQSJ7bqBzbcAPtnM7zazmxiS:mh_2AohoUhCChdtoNSZPYsjHimAmY2VPH5aU8N9VJWi9gDHf9hrPC:15765745514Ú_d```
The first number is the key-block it has observed, the last number 15765745514 is posix timestamp.  This timestamp can be compared with the micro-block time stamp we find it in.

**Comment by ThomasArts** [comment]
Block propagation time can be a metric locally. A node can compare the incoming key-block (or micro-block) and compare the timestamp in that block with local time. This is not guaranteed to be the real propagation time, it could even be negative if clocks drift or miners are not completely honest, but it's an indication and relatively easy to add.

**Comment by dincho** [comment]
> Number 1) is tricky. If you post a transaction and get it returned, you could get it returned from your neighbouring node. There is no guarantee that more than you and your neighbour actually have received the Tx... We have no hop-count in gossip messages.

Maybe we should report the RTT of the transaction for each peer that it's received from, this way we can have some more details and more meaningful numbers ? 🤔

**Comment by tolbrino** [comment]
Closing this as more metrics are handled in a different task.
