### ISSUE TITLE
Migrate release packages from OTP 20 to OTP 21

### ISSUE THREAD

**Issue by tolbrino** [aeternity/aeternity#3104]
Right now the node is compatible with OTP 20 and 21, but we are shipping the release with OTP 20. The improvement of going to OTP 21 is 1+ year worth of bug-fixes and improvements in OTP, which has a direct impact on how the node is run by users.

**Comment by uwiger** [comment]
We are now on OTP 22. Closing

**Comment by deMaxli** [comment]
Hi there, I am new here (on Gitihub) and familiarizing myself with AE. After my initial research, I was keen to learn whether hyperchains have already been implemented and how they work? I couldnt find more on the project (hyperchain) here but maybe I am just not getting gitihub ;) Cheers
