### ISSUE TITLE
Update rocksdb to 6.4.6

### ISSUE THREAD

**Issue by tolbrino** [aeternity/aeternity#3113]
The node is currently using rocksdb version `5.15.10`.

One issue with this upgrade is that rocksdb switched to using cmake, thus the build process will need to be adapted accordingly.

### Useful Links

[rocksdb Changelog](https://github.com/facebook/rocksdb/blob/master/HISTORY.md)

**Comment by radrow** [comment]
If somebody has problems with the current build they can try adding `CXXFLAGS="-Wno-error=shadow -Wno-deprecated-copy -Wno-redundant-move -Wno-pessimizing-move"` env variable to dismiss some errors that cause the issues
