### ISSUE TITLE
Add new seed nodes to default config

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#3119]
We plan to add few more mainnet seed nodes and they should be added to the sys.config

**Comment by tolbrino** [comment]
Are these nodes up yet?

**Comment by dincho** [comment]
> Are these nodes up yet?

nope

**Comment by dincho** [comment]
@tolbrino it's setup now, we're monitoring their stability

**Comment by dincho** [comment]
This seems outdated, the new seed nodes are already in the distribution.
