### ISSUE TITLE
SC: inconsistent conflict messages

### ISSUE THREAD

**Issue by AleksandarFilipov** [aeternity/aeternity#3120]
## Expected Behavior

Consistent conflict message is expected

## Actual Behavior

Inconsistent messages

## Steps to Reproduce the Problem

Alice: Start a transaction, sign the transaction
Bob: start a transaction, sign the transaction
- conflict message will appear, unexpected error format according to snippet below

Alternatively

Alice: Start a transaction, sign the transaction
Bob: start a transaction, sign the transaction
- conflict message will appear, with *expected* error format

## Details
normally when i get a conflict it matches this clause
```
def process_message(
        %{
          "method" => "channels.conflict" = method,
          "params" => %{
            "channel_id" => channel_id,
            "data" => %{"round" => round, "channel_id" => channel_id2}
          }
        } = _message,
        %__MODULE__{channel_id: current_channel_id} = state
      )
```
but for some reason i get error message according to following format, containing a conflict
```
%{
      "channel_id" => "ch_2KKQ2CXGHvmhyZKxRfbQ7d1Led4uV5qEL7ztcZGsy9AkDk2pxj",
      "error" => %{
        "code" => 3,
        "data" => [%{"code" => 107, "message" => "Conflict"}],
        "message" => "Rejected",
        "request" => %{
          "jsonrpc" => "2.0",
          "method" => "channels.update.new",
          "params" => %{
            "amount" => 10,
            "from" => "ak_cFBreUSVWPEc3qSCYHfcy5yW2CWkbdrPkr9itgQfBw1Zdd6HV",
            "to" => "ak_SVQ9RvinB2E8pio2kxtZqhRDwHEsmDAdQCQUhQHki5QyPxtMh"
          }
        }
      },
      "id" => nil,
      "jsonrpc" => "2.0",
      "version" => 1
    }
```

**Comment by uwiger** [comment]
Seems related to #3004

**Comment by velzevur** [comment]
Managed to reproduce in a test
