### ISSUE TITLE
SC: websocket is not closed on "invalid fsm id"

### ISSUE THREAD

**Issue by AleksandarFilipov** [aeternity/aeternity#3163]
## Expected Behavior

> **Might need an extra discussion whether this is expected behaviour or not.** 

When reestablishg using incorrect `fsm_id` (correct `channel_id`) websocket should _probably_ be terminated.
...

## Actual Behavior

```json
{
    "channel_id": null,
    "error": {
        "code": 3,
        "data": [
            {
                "code": 1016,
                "message": "Invalid fsm id"
            }
        ],
        "message": "Rejected",
        "request": {}
    },
    "id": null,
    "jsonrpc": "2.0",
    "version": 1
} 
```

## Steps to Reproduce the Problem

  1. reestablish using incorrect fsm_id

**Comment by velzevur** [comment]
I've done a lot of tests and this is not a bug :)

Yes, indeed we open a WebSocket connection, then we try using the invalid `fsm_id` we send the message above and then close the WebSocket connection.
