### ISSUE TITLE
Arch linux install docs

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#3179]
Verify the support and add documentation how to install the node in arch linux.

Make sure that the documentation is clear that it's not "officially" supported, that is it's no verified by CI.

**Comment by tolbrino** [comment]
So you want to add it to the pacman community package repository?

**Comment by dincho** [comment]
> So you want to add it to the pacman community package repository?

No, just few additional lines in the build docs, how to build it on arch

**Comment by radrow** [comment]
Actually, would be nice to have it in AUR I think

**Comment by gorbak25** [comment]
Ok I will handle it and maintain 2 AUR packages:
- aeternity
- aeternity-git
Perhaps I might modify the release CI pipeline to autorelease the aeternity package
