### ISSUE TITLE
Update key header info field to latest node version

### ISSUE THREAD

**Issue by tolbrino** [aeternity/aeternity#3185]
Is done here: https://github.com/aeternity/aeternity/blob/master/apps/aecore/include/blocks.hrl#L15

Should be either part of the release steps in https://github.com/aeternity/aeternity/wiki/Release-process or even done automatically through the `VERSION` file via make or such.

**Comment by dincho** [comment]
This should be definitely automatic. A release process should not have any manual steps besides tagging the release itself. We already have a lot of manual steps, so let's get rid from this one at least.

**Comment by uwiger** [comment]
Solved in PR #3552 - closing
