### ISSUE TITLE
Using 'enoise_send' is better than 'enoise:send'

### ISSUE THREAD

**Issue by callbay** [aeternity/aeternity#3217]
https://github.com/aeternity/aeternity/blob/0f25ff8b8ee5cab82f3ddcdf3ad0f58eea47900d/apps/aecore/src/aec_peer_connection.erl#L1216

Error can be caught when a message fails to be sent.

**Comment by tolbrino** [comment]
Hi @callbay. A PR would be greatly appreciated.
