### ISSUE TITLE
ForceProgress transaction has no info on-chain

### ISSUE THREAD

**Issue by nduchak** [aeternity/aeternity#3229]
## Expected Behavior
Can retrieve info about Force Progress tx
...

## Actual Behavior
ForceProgress transaction has no info on-chain
...

## Steps to Reproduce the Problem

  1. Open channel
  1. Create contrcat
  1. make force progress tx, sign and send it to the chain(using WS API or manually)

## Specifications

  - Virtualization: [*none / metal / container / VM*]
  - Hardware specs:
    * RAM:
    * CPU:
  - OS: [*distribution, version*]
  - Node Version: 5.5.0

**Comment by velzevur** [comment]
This is already done in #3248 and I tested it is working. Closing the issue
