### ISSUE TITLE
Cannot download the database snapshot

### ISSUE THREAD

**Issue by zenghq3** [aeternity/aeternity#3234]
## Expected Behavior

Get the database snapshot

## Actual Behavior

`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>90EE7F874AA39130</RequestId><HostId>lwfapG7SozTKBYQ8iihPUmOkjCoHEfj0gpU9CW7QGs1u4hNzrWInCRonFe5IXoOdl4JA1eJHCVA=</HostId></Error>`

## Steps to Reproduce the Problem
`curl https://aeternity-database-backups.s3.eu-central-1.amazonaws.com/mnesia_main_v-1_latest.tgz`

**Comment by tolbrino** [comment]
@zenghq3 Where is the above links from originally?

**Comment by dincho** [comment]
The URL is actually correct, they probably got it from https://downloads.aeternity.io

I'd suggest to use timestamped snapshots, as the `latest` one is ofter overwritten and temporary unavailable - or plan for enough retries with exponential backoff time

**Comment by dincho** [comment]
> I'd suggest to use timestamped snapshots, as the `latest` one is ofter overwritten and temporary unavailable - or plan for enough retries with exponential backoff time

Also, basic short retry could improve that.

I'm closing it for inactivity and I've provided a workaround/solution.
