### ISSUE TITLE
Check on-chain state before trying to reestablish

### ISSUE THREAD

**Issue by uwiger** [aeternity/aeternity#3237]
## Expected Behavior

When trying to reestablish with the latest known off-chain state, the FSM should check the on-chain state in order to detect any unilateral updates (close_solo or force_progress). If there is a force-progress, the FSM needs to update its off-chain state in order to proceed with the reestablish.

## Actual Behavior

The FSM doesn't check the on-chain state. Therefore, if the state has been force-progressed, the reestablish will fail. If the on-chain channel has been solo-closed, the reestablish will fail, and the FSM will not even accept a `slash` request from its client.

## Steps to Reproduce the Problem

  1. Start a channel
  1. Initiator leaves, responder stays
  1. Responder force-progresses a contract
  1. Initiator tries to reestablish

## Configuration, logs, error output, etc.

- `aeternity.yaml` configuration file

```
---
REPLACEME
some_config:
```

- From the test log output of a locally modified state, where the responder has done a close_solo before the initiator tries to reestablish. The initiator does not report any change, and if the client tries to slash, it rejects the request.

```
=== Location: [{aesc_fsm_SUITE,perform_slash,4354},
              {aesc_fsm_SUITE,slash_while_awaiting_connect,4396},
              {test_server,ts_tc,1546},
              {test_server,run_test_case_eval1,1062},
              {test_server,run_test_case_eval,994}]
=== Reason: no match of right hand side value {error,channel_not_closing}
  in function  aesc_fsm_SUITE:perform_slash/2 (/home/uwiger/ae/6/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl, line 4354)
  in call from aesc_fsm_SUITE:slash_while_awaiting_connect/1 (/home/uwiger/ae/6/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl, line 4396)
  in call from test_server:ts_tc/3 (test_server.erl, line 1546)```

## Specifications

  - Virtualization: [*none / metal / container / VM*]
  - Hardware specs:
    * RAM:
    * CPU:
  - OS: [*distribution, version*]
  - Node Version:

**Comment by velzevur** [comment]
Since this had been already fixed, I am closing the issue
