### ISSUE TITLE
AENS: Increase the name expiry time

### ISSUE THREAD

**Issue by hanssv** [aeternity/aeternity#3280]
- [x] Make a vote on how long it should be (3m, 6m, 1y?)
- [ ] Change the constant (and make it height dependent!)
- [ ] Adapt the tests

**Comment by velzevur** [comment]
This appeared more than once in the Forum

**Comment by velzevur** [comment]
As we've discusses, this should be done via the governance app where some preset options are provided to the stakeholders to vote on

**Comment by hanssv** [comment]
Poll number 36
