### ISSUE TITLE
AENS: Review and simplify pointers

### ISSUE THREAD

**Issue by hanssv** [aeternity/aeternity#3282]
- [ ] Check what is really enforced right now
- [ ] Adapt to something more strict (if necessary), restrict the number of pointers, the order(?), etc.
- [ ] Update tests to cover this

**Comment by hanssv** [comment]
https://forum.aeternity.com/t/pointer-key-with-multiple-values/6024
https://github.com/aeternity/aeternity/pull/2684

Some references that can be useful - also see #core-ns in Rocket.chat

**Comment by uwiger** [comment]
Done. Closing
