### ISSUE TITLE
AESC: new transaction type - set delegates

### ISSUE THREAD

**Issue by velzevur** [aeternity/aeternity#3288]
Currently delegates can only be set at channel creation time which makes no sense for long running channels.

**Comment by hanssv** [comment]
Remind me, the delegates are those that are entrusted to act on your behalf (during closing of the channel)? If so, yes it makes sense to be able to update those. 

I assume it should be a mutually signed TX?

**Comment by velzevur** [comment]
Yes - they are the trusted parties, yes - it must be a mutually signed tx
