### ISSUE TITLE
Sync: cleanup dead peers

### ISSUE THREAD

**Issue by velzevur** [aeternity/aeternity#3290]
This had been discussed over and over again. There are still quite a lot of dead peers that are being sent around.

Related issues:
#3114

**Comment by dincho** [comment]
This should be taken care carefully.
To the one who would work on this, please make sure you read and **understand** the documentation on the topic:
- https://github.com/aeternity/protocol/blob/master/GOSSIP.md
- https://github.com/aeternity/protocol/blob/master/SYNC.md
- https://github.com/aeternity/aetmodel/blob/master/ThreatModel.md

**Comment by uwiger** [comment]
Solved by e.g. #3365 - closing.
