### ISSUE TITLE
Drop "native" windows support

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#3299]
It's unclear why would anyone ever run a node in windows, we should find if there is even single user of it.

We don't release windows package since 5.4.1 because of broken builds and there are no complains yet.

**Comment by velzevur** [comment]
If we do this, then #3228 would be obsolete

**Comment by velzevur** [comment]
We need to bring this to the forum for a discussion.

**Comment by radrow** [comment]
Won't the node run on WSL anyway?

**Comment by dincho** [comment]
> Won't the node run on WSL anyway?

Yes, but cannot mine IIRC
