### ISSUE TITLE
Rest API endpoints version prefix

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#3300]
Rest API endpoints version prefix should be bumped with the node major. Currently the version endpoint prefix is hardcoded to `v2` in the URL, this is plainly wrong and currently useless.

The prefix should reflect major (backward incompatible) API changes to signal users and machines about the fact.

An example use case is caching layers, e.g. block 1337 can be cached "forever" until its API structure changes for some reason, and changing the prefix will technically invalidate the cache.

**Comment by velzevur** [comment]
This is not relevant anymore.
