### ISSUE TITLE
Missing local_lima_testnet setting

### ISSUE THREAD

**Issue by velzevur** [aeternity/aeternity#3435]
There is a missing `local_lima_testnet` [here](https://github.com/aeternity/aeternity/blob/master/apps/aecore/src/aec_hard_forks.erl#L108-L135)

kudos to Marcolo for finding it.

**Comment by velzevur** [comment]
After further analysis - any network id except the `local_(roma|fortuna|minerva|iris)_testnet` would act as `local_lima_testnet` (including `local_lima_testnet` itself). Since this is the default protocol now, this is ok. It will change with `iris` hard fork, so this is required as soon as 6.0.0

**Comment by marc0olo** [comment]
please view my latest comment https://forum.aeternity.com/t/aeternity-roadmap-and-release-schedule-q4-2020-q1-2021/8201/32?u=marco.chain and consider adding it in 5.6.0

**Comment by velzevur** [comment]
I see this could improve the behaviour of the MDW. It will be part of 5.6.0
