### ISSUE TITLE
Configurable resistance to forks injected via sync

### ISSUE THREAD

**Issue by uwiger** [aeternity/aeternity#3463]
The discussion below outlines how to address resistance to long forks being injected via the sync protocol (note, long forks are already rejected when injected via gossip).

The suggested approach is to let the node have a "confirmation time", much in the same way as when users confirm their own transactions: at a configurable depth, the chain becomes explicitly unwilling to fork. The nature of POW mining requires the ability to handle short forks resulting from natural race conditions. However, these should not go deeper than 1 key block.

## Introduction
In a proof-of-work (POW) blockchain system, it is possible to attack a network with brute force ("51% attack"): if you control enough mining resources to out-mine the rest of the network, you can essentially go back and rewrite history.

This can be realised in the following type of attack (by attacker 'A'):
1. `A` buys value on the chain. This will contribute to driving up the value of the chain token, at least on a fairly small chain.
2. `A` prepares a mining rig, syncs up with the chain, perhaps mines a few blocks on the main chain as a test run.
3. `A` then starts e.g. buying some other coin that is hard to trace. The exchanges may require a verification period of 500 blocks (or even more), but will eventually approve the transactions.
4. Meanwhile, `A` disconnects the mining rig from the main network, and secretly builds a block history where the transactions in (3) are not included.
5. Once the alternative history has a significantly greater height than the main chain, `A` reconnects the mining rig, and the sync protocol will instruct the main chain nodes to accept the longer fork.
6. The transactions in (3) are now no longer on the chain, and `A` was able to purchase external coin _and_ get all the money back.

At one level, this is perfectly in line with the protocol, and expectations of POW systems. Still, we would like to have some automatic protections, at least making it less profitable to do this.

## One-time fix: Whitelist
In the last attack, we were able to spot the buildup (steps 2 and 3 above), causing us to suspect that (4) was underway. We made a secret emergency patch where our block insertion logic checked a 'whitelist', which authoritatively specified which block hashes were expected at given heights. This seems to have worked since (a) the miners and exchanges accepted our solution, and authoritative view of the world, and (b), we were able to start fielding this (minutes) before the attack (step 5) was initiated.

An obvious problem with this is that it's a one-off, and the manually injected whitelist can only protect against attacks that have already gone through steps 1 - 3 above; it will be ineffective against future attacks.

### Automatically reject long forks
By setting a chain verification depth `D`, the block insertion logic can reject blocks that initiate or build on a fork which splits from the current main chain before height `Top() - D`. This would make nodes resistant to attacks introducing a history rewrite via the sync protocol.

A drawback would be that if a node happens to find itself on the 'wrong' fork, it will resist switching to the 'right' fork, even if it eventually outmines the 'wrong' fork.

To mitigate this, it should be straightforward to change the setting: if you set `D` to a very large number, the node will accept even very long forks. An alternative way to instruct the node which is the preferred fork would be to specify a block hash expected to be on the preferred fork. These two methods are complementary.

### Directed sync
Related to the above, extend the sync protocol so that the node can select peers based on who have a certain block hash on the main chain.

Another possible parameterization of the sync is to specify a height from which to start selecting peers. Currently, the sync implementation takes its own top and checks whether there are any connected peers that have that hash (and a greater height). This can be problematic if recent events have taken your node in an unwanted direction. To address this, one can:
1. Delete the database and sync from scratch. This is a very slow method
2. Download a new database snapshot and sync from that. This can also be very slow, depending on the download speeds.
3. Run a script that rolls back your database to a given height.
4. Set a parameter that selects peers based on a previous height, not necessarily favoring own data above that height.

Alternative no 4 runs the risk of resulting in some garbage in the database, in the form of orphaned blocks and state tree objects. This is not likely to interfere with operations.

## Discussion
Looking at the one-time fix described above, one can question why the whitelist needs to be a range of blocks. It seems as if a single hash should suffice, especially if it's a blockhash some distance away from the top.

It is also worthwhile to consider the expectations of users of the chain. When discussing reliability of transactions, it is normal to speak of _confirmation time_, i.e. how many blocks should pile up on top of your transaction in order for it to be secure. A common rule of thumb is 6 key blocks, and one can calculate the cost of brute-forcing the chain just to evict a transaction buried `X` blocks beneath the top.

With high-value transactions, it is reasonable to wait longer. The idea of "zero-confirmation" reflects the fact that in some situations, even waiting for _one_ new keyblock is too long (consider standing at the cashier's to pay for coffee, or using [Vereign](https://vereign.com) to auto-seal an email when pressing the 'Send' button. In these cases, Aeternity's Bitcoin-NG protocol offers the alternative of waiting for a _microblock_ confirmation, which normally takes up to 3 seconds. On the high-value end, exchanges may wait 500 keyblocks (roughly 25 hours), or even longer, before approving a transaction. This starts feeling counter-productive, scaring people away from trading.

A complication for exchanges is that a brute-force attack, since it takes quite a bit of planning and preparations to set up, and stealth is desired, is unlikely to target just a single transaction. Rather, they not only spread the attack across many smaller transactions, but also across several different miners. This makes it hard for exchanges to gauge the total potential profit, and thus cost-benefit calculation, for the attacker. Even if this sort of estimate could be derived from the chain (which is transparent enough to do so), raising the confirmation time to thousands of blocks again hurts users of the chain and of the exchanges.

Based on this, it seems reasonable for nodes on the blockchain to make themselves fork resistant at some reasonable depth - say, `100` blocks. This should not affect the eventual consistency workings of inevitable collisions and resulting forks, as these resolve much quicker than that. The gossip protocol already protects against blocks which are a configurable distance from the top (`sync:gossip_allowed_height_from_top` - default: `5`), so to stage a larger rollback attack, one needs to introduce the new fork via the `sync` protocol. It seems reasonable that nodes which are in sync and operating via the `gossip` protocol resist being hijacked into a new history that begins long before what is seen as reasonable confirmation time by the users.

A beneficial consequence of this should be that there is little reason for exchanges to use confirmation times much longer than the nodes' fork resistance depth. Once this has been reached, a rollback attack will be extremely difficult.

### Accidental netsplits
Aeternity did suffer a netsplit about a year ago, which looked very much like a 51% attack, but was actually accidental. At the time, the chain had few miners, and the dominant mining pool, in Wuhan, China, suffered connectivity problems. Once it reconnected with the chain, it had managed to create an 'alternative history' (at least from the perspective of the rest of the world) of 700 blocks, which overtook the chain and caused much confusion.

In this particular scenario, no one actually lost money, except some miners whose blocks were evicted. What would have happened if dynamic fork resistance had been implemented, is that the nodes on the 'main chain' would have rejected the Wuhan fork, and the miner would be faced with the decision of either convincing the main net to accept the longer fork, or syncing up to the main chain itself. This would then have to be a conscious decision, and a negotiation between the affected parties, but arguably, this is how it should be.

## Alternatives
The above protection is very simplistic, basically just mimicking the confirmation time already familiar to the users. This could also be said to be its main strength.

One could also imagine performing a more sophisticated analysis of competing forks, calculating some form of "goodness metric". Cardano has a concept of "entropy", where they have observed that certain types of attacks produce forks that are qualitatively different than those that result from normal operation. Mind, Cardano is a PoS system, so milage may differ.

Looking at what such an analysis could look like on a PoW chain like Aeternity, we can observe only a few things:
* Identity of the leader. Unfortunately, as the keyblocks are not signed, it is possible to fake the account ID. Such a keyblock would never be followed by microblocks, which _are_ signed, with a key that much match the keyblock pubkey. Thus, for the analysis, we would have to ignore empty generations.
* Variety of leaders. Naively, an attacker might be expected to mine all blocks from the same account. However, the recent attacker didn't do this, but rather used a variety of mining accounts that wasn't too different from what we normally see on Aeternity. In other words, given the actually pretty low variety of miners on Aeternity, this sort of analysis is very hard to rely on.
* One could imagine an analysis that takes a longer history into account, such that we will give greater credence to miners that have contributed significantly to the chain for a longer period of time. Intuitively, this feels like it could backfire in a number of ways. Also, a sufficiently sophisticated, but yet deterministic metric would need to be performed inline at each block insertion, and be documented as part of the protocol. Presumably, it could be some form of sliding-window integral of the mining rewards.

**Comment by radrow** [comment]
I completely support this idea. It is worth noting that this solution is already implemented in other blockchains, such as NXT [[1]](https://nxtdocs.jelurida.com/Nxt_Whitepaper#History_Attack). Though it may be problematic for syncing nodes, I believe it would be relatively easy for them to discover the "most popular" branch and attach to it (especially with eventual audit from aeternity's side if the deal would be significant).

**Comment by uwiger** [comment]
In my prototype implementation, the fork resistance is activated only when sync has been completed with at least one peer.

I'm currently thinking about how this can be tweaked without causing unintended results while syncing.
I'm thinking that there should be a way to instruct the node to apply fork resistance even during sync.

**Comment by gorbak25** [comment]
Sync could be extended so any new node first tries to find the most "certain" block hash/fork available and only then sync with it. Unfortunately this might be circumvented easily as:
1. An attacker might spawn multiple nodes essentially spamming the network with bad nodes
2. It's not BFT
