### ISSUE TITLE
Generalized database rollback support

### ISSUE THREAD

**Issue by uwiger** [aeternity/aeternity#3468]
Related to #3463, we should generalize a technique used to quickly get users prepared to move away from a fork they didn't want to be on.

Suggestion: create an aeternity extension script for rolling back the chain database to a given height or hash.
This way, esp combined with the whitelisting support (issue #3467), it should be straightforward to revert an unwanted fork injection and re-sync against a desired fork.

**Comment by gorbak25** [comment]
Suggestion:
Keep track of a hash we consider "finalized" - if the current top is not a direct predecesor of the finalized hash we iterate the chain-ends from #3470 and take the "next best block" which is a direct predecessor of the finalized hash. No DB deletes would be required.

**Comment by uwiger** [comment]
Deleting unwanted blocks would still be desirable from a housekeeping perspective, though.

**Comment by uwiger** [comment]
Solved in PR #3704
