### ISSUE TITLE
Accounts endpoint return wrong nonce for some time after a transaction is mined

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#3516]
I have noticed that the `accounts` endpoint returns an increased (correct) nonce right after the transaction is mined, but after that, it returns the previous one for several subsequent requests.

I have written a script to reproduce it, trying to use SDK as little as possible. That script makes spend transactions one by one and after one of them is mined it requests the current nonce several times, comparing it with the nonce node should return.

## Steps to reproduce
- clone https://github.com/aeternity/aepp-sdk-js/tree/reproduction/nonces
- run `docker-compose up -d`
- run `npm i && npm run build`
- run `node ./reproduction.js`
- wait for mining of about 50-500 transactions
- script should end up with an output like:
```
...
spend 65 171
spend 65 172
spend 65 173
spend 65 174
current nonce 174
nonces [
  174, 173, 173, 173, 173, 174, 174,
  174, 174, 174, 174, 174, 174, 174,
  174, 174, 174, 174, 174, 174, 174,
  174, 174, 174, 174, 174, 174, 174,
  174, 174, 174, 174, 174, 174, 174,
  174, 174, 174, 174, 174
]
```

## Additional context

Currently, the tests in the SDK repository fail in random places, and I'm working on fixing them. I think this nonce issue breaks the tests in some cases.

**Comment by davidyuk** [comment]
The reproduction above is based on a node with a fast mining configuration:
```
expected_mine_rate: 1000
micro_block_cycle: 200
```
but, actually, it is reproducible on slower configurations, like:
```
expected_mine_rate: 4000
micro_block_cycle: 1000
```

**Comment by velzevur** [comment]
This looks like mining related indeed, the following setup was working till nonce 731 without any issue:
```
diff --git a/docker/aeternity_node_mean16.yaml b/docker/aeternity_node_mean16.yaml
index 3fe6f38..9c87397 100644
--- a/docker/aeternity_node_mean16.yaml
+++ b/docker/aeternity_node_mean16.yaml
@@ -29,8 +29,8 @@ chain:
 mining:
   autostart: true
   beneficiary: "ak_2iBPH7HUz3cSDVEUWiHg76MZJ6tZooVNBmmxcgVK6VV8KAE688"
-  expected_mine_rate: 1000
-  micro_block_cycle: 200
+  expected_mine_rate: 180000
+  micro_block_cycle: 3000
   cuckoo:
     miner:
       executable: mean15-generic
```

**Comment by davidyuk** [comment]
How to proceed with it? Fixing this would significantly improve developers' experience in cases like running automated tests of a smart contract.

**Comment by velzevur** [comment]
I've opened a fix for this in the JS-SDK API but since I have no access there, I had to open it via my own fork and I am unable to add reviewers. cc @davidyuk

**Comment by davidyuk** [comment]
Looks like that I'm completely satisfied with `strictly_follow_top: true` approach, thank you!
