### ISSUE TITLE
Support starting Aeternity node in "debug mode"

### ISSUE THREAD

**Issue by uwiger** [aeternity/aeternity#3545]
When debugging issues in a mainnet node, it would be very helpful to be able to disable sync, and likely also the HTTP endpoints, without having to start from an entirely different configuration. This also becomes highly relevant for the work on the `db_rollback` script (issue #3468): a database rollback should not be performed on a live node, esp. while sync and/or mining are active.

One way to achieve this could be to define a config variable, e.g. `debug_mode`, which defaults to `false`. Starting a node with `AE__DEBUG_MODE=true bin/aeternity start` could then bring up a node, which - detecting the config - doesn't bring start mining, sync or external endpoints.

The `db_rollback` script would then abort if the target node is not in debug mode.

**Comment by dincho** [comment]
Reading the requirements and the use-case may I recommend using a "maintenance mode" instead of debug? It somehow represents better the idea in my head

**Comment by dincho** [comment]
Also, if possible, it would be nice if this mode can be toggled runtime (bin/aeternity enable/disable commands or similar)

**Comment by uwiger** [comment]
Sure, maintenance mode is better.

I think toggling at runtime might be done as a future step. It would certainly be useful, but it needs to work reliably.

**Comment by velzevur** [comment]
Implemented in #3702, closing this one.
