### ISSUE TITLE
swagger schema definiton PayingForTx

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeternity#3566]
I just started implementing support for the PayingForTx in the Java SDK (https://github.com/kryptokrauts/aepp-sdk-java/issues/139) and I am wondering that there is no schema definition for this tx-type.

is there any reason this isn't included or did you just forget it? @velzevur

**Comment by velzevur** [comment]
Yep, we will add it

**Comment by velzevur** [comment]
@marc0olo once the related PR is merged, there will be support for `paying_for_tx`. Additionally I added a `debug` endpoint in the internal HTTP API to produce correct `paying_for_tx` for you, as long as you provide a `payer_id`, `fee` and `tx` you are paying for (which comes with its signatures). If the inner transaction authentication is invalid - you get a proper message just to know where to look at :)
