### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by heiheshang** [aeternity/aeternity#3572]
===> Compiling c_src/lz4.c
===> Compiling c_src/lz4_nif.c
===> Compiling c_src/lz4hc.c
===> Compiling /home/oper/Programs/aeternity/c_src/enacl_nif.c
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`

**Comment by gorbak25** [comment]
@heiheshang Hi!
Could you provide me the full logs with DIAGNOSTIC=1 ?

**Comment by heiheshang** [comment]
[error.log](https://github.com/aeternity/aeternity/files/6242759/error.log)

**Comment by heiheshang** [comment]
Error: badarg
[]

**Comment by gorbak25** [comment]
@heiheshang On which OTP version you try compiling the node?

**Comment by heiheshang** [comment]
Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

**Comment by arpunk** [comment]
@heiheshang are you trying to build from `master` branch?

**Comment by gorbak25** [comment]
Try on OTP22

**Comment by heiheshang** [comment]
> @heiheshang are you trying to build from `master` branch?

yes

**Comment by heiheshang** [comment]
> Try on OTP22

I've been trying to start for a long time, different releases, I have never been able to start yet, the error is the same

**Comment by velzevur** [comment]
> I've been trying to start for a long time, different releases, I have never been able to start yet, the error is the same

Did you try compiling under OTP22?

**Comment by gorbak25** [comment]
Are you using our Makefile?

**Comment by heiheshang** [comment]
> Are you using our Makefile?

yes

**Comment by ThomasArts** [comment]
We support OTP24 and above.
If compile problems persist, please ask the forum
