### ISSUE TITLE
Cannot compile with Apple M1

### ISSUE THREAD

**Issue by cna0** [aeternity/aeternity#3632]
I'm trying to build the project on Mac M1, but NIFs fail to compile. I cannot pass through compiling the [emcl](https://github.com/aeternity/emcl) dependency, so I'm not sure if there's any other dependency having the same issue. However, https://github.com/herumi/mcl/commit/b0abe614ae838470d000b6ccc5025803401d4053 has added support for M1 which is not included in emcl.

**Comment by marc0olo** [comment]
this is interesting. @omar-saadoun was trying to run the new node versions in our development tool aeproject and he also faced problems with his Apple M1.

he isn't able to run the docker-image of the node due to this issue: https://github.com/docker/for-mac/issues/5148

cc @mradkov

**Comment by omar-saadoun** [comment]
Thanks @marc0olo like you said this is related to https://github.com/aeternity/aepp-aeproject-js/issues/376

**Comment by cna0** [comment]
The simplest workaround I found was to enable Rosetta for the Terminal and then compile the project (of course without Docker).

**Comment by omar-saadoun** [comment]
May be it will work for the node itself but I think it won't for aeproject

**Comment by earlyriser99** [comment]
I played with this a bit. Updating the git submodule in emcl so its mcl points to the latest version allows the build process to complete.

Unfortunately this wasn't enough to get the node up and running. The enacl build is not linking libsodium.so to its nif. I tried changing the enacl rebar.config to explicitly build arm64 instead of x86-64, but the link step then complained about linking incompatible architectures.

Possibly my lib sodium.so was built wrong. More work needed

**Comment by subhod-i** [comment]
@earlyriser99 What about re-installing the arm64 libsodium? this might resolve the `linking incompatible architectures` issue.

**Comment by subhod-i** [comment]
Support and publishing docker image for platform arm64 is important as arm64 becomes mainstream.

**Comment by seanhinde** [comment]
An update: I now have a native build running locally on my machine.

Next step is to incorporate all the manual steps into the proper build of the node and document the process.

After that I can take a look at an arm64 docker build.

**Comment by subhod-i** [comment]
@seanhinde Thanks for the quick update. I know the current native build fix is not documented, can you guide us on running the native build?
Compiling node manually on the terminal with Rosetta2 shall work right?

**Comment by marc0olo** [comment]
> After that I can take a look at an arm64 docker build.

I know such question is sometimes hard to answer 😅 - do you have a **_rough_** estimate for this?

**Comment by seanhinde** [comment]
I'm planning to have a go at tidying this up this weekend. At the moment I only have evening and weekend access to the m1 machine..

**Comment by seanhinde** [comment]
> @seanhinde Thanks for the quick update. I know the current native build fix is not documented, can you guide us on running the native build?

There are some changes needed to aeminer so it's not just documenting a process. It should be seamless when I'm done.

> Compiling node manually on the terminal with Rosetta2 shall work right?

This I have not tried.

**Comment by seanhinde** [comment]
Darn. I lose the m1 machine this weekend. Will be next week now.

**Comment by omar-saadoun** [comment]
@seanhinde I have M1. Can I help you somehow?

**Comment by seanhinde** [comment]
Not right now, but I'll see if I can find a way to use you as the test subject - a few branches need to come together across a few of our repos as well.

**Comment by seanhinde** [comment]
There is a branch at https://github.com/aeternity/aeternity/tree/gh-3632-apple-arm-m1-support

Right now for me it all builds cleanly so long as the normal dependencies libsodium,  libgmp etc are available as native arm libs

I'd appreciate it if a few more folks could try this branch on their machine before pushing to the mainline. @omar-saadoun ?

There is one failing unit test for me at the moment

```
git clone https://github.com/aeternity/aeternity
cd aeternity
make
make eunit-latest
make ct-latest
```

**Comment by omar-saadoun** [comment]
I'm getting this error after make command:

env: escript: No such file or directory
make: *** [internal-compile-deps] Error 127

**Comment by seanhinde** [comment]
You need to have erlang installed as well

**Comment by omar-saadoun** [comment]
Hmm...I'm supposed to have it already any particular  procedure?

**Comment by seanhinde** [comment]
More investigations led to this procedure:

Following the instructions at [Build from Source](https://docs.aeternity.io/en/stable/build/) with the following differences:

`brew install cmake`

Then before running `make` in the checked out branch run:

```
export PATH=/opt/homebrew/bin:$PATH
export CFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"
```

**Comment by subhod-i** [comment]
@seanhinde since the FIX is in master, I was trying to pull the latest master tagged docker image from the hub and try running it. Encountered the same error where the container exited in a few seconds.

Native binary I am able to build.

**Comment by marc0olo** [comment]
@subhod-i I think @thepiwo opened a new issue for that, see #3799

**Comment by seanhinde** [comment]
Closing this one with a final PR to update the docs with details from this ticket https://github.com/aeternity/aeternity/pull/3820
