### ISSUE TITLE
new external HTTP endpoint: /dry-run returns 404 not found

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeternity#3635]
@velzevur I tried to use the new endpoint yesterday and it seems like it cannot be used right now. for some reason the node returns status code `404` when I try to call it

**Comment by velzevur** [comment]
@marc0olo did you enable this endpoint? It is disabled by default. You can read more about it here:
https://github.com/aeternity/aeternity/pull/3628#pullrequestreview-661035888

**Comment by marc0olo** [comment]
@velzevur yeah I should have read the release notes in more detail. I passed the message where you stated it's disabled by default.

I just enabled it and I struggle to understand how the gas limit is calculated. I needed to increase the configured gas_limit heavily to get my integration tests in the SDK working against the endpoint, though I passed < 6 000 000 gas to the dry-run.

additionally for every of those calls the node returned lot less gas to be consumed by the call. some examples for the gas usage (returned by the node) of the calls I am talking about:
- `3767` (init)
- `21705` (payAndSplit)
- `2021` (getTotalAmountSplitted)
- `2045` (getOwner)

I am talking about this contract which I am testing right now:

```
payable contract PaymentSplitter =
   record state =
      {  owner: address,
         recipientConditions: map(address, int), // map of recipients with percentage to receive (value between 1 and 100)
         totalAmountSplitted: int }

   // CONTRACT EVENTS
   datatype event = AddingInitialRecipients()
      | RecipientAdded(indexed address, indexed int)
      | AddressUpdated(indexed address, indexed address)
      | UpdatingAllRecipients()
      | PaymentReceivedAndSplitted(indexed address, indexed int, indexed int)

   // CONSTRUCTOR
   entrypoint init(recipientConditions': map(address, int)) : state =
      require(sumWeights(recipientConditions') == 100, "sum of weights needs to be 100")
      Chain.event(AddingInitialRecipients)
      {  owner = Call.caller,
         recipientConditions = recipientConditions',
         totalAmountSplitted = 0}

   // READ ONLY FUNCTIONS

   entrypoint getOwner() : address =
      state.owner

   entrypoint getRecipientsCount() : int =
      Map.size(state.recipientConditions)

   entrypoint isRecipient(who': address) : bool =
      Map.member(who', state.recipientConditions)

   entrypoint getWeight(who': address) : int =
      Map.lookup_default(who', state.recipientConditions, 0)

   entrypoint getTotalAmountSplitted() : int =
      state.totalAmountSplitted

   // PAY-AND-SPLIT FUNCTION
   stateful payable entrypoint payAndSplit() =
      require(Contract.balance > 0, "contract didn't receive any payment")
      let recipientConditions: list(address * int) = Map.to_list(state.recipientConditions)
      put(state{totalAmountSplitted = Contract.balance + state.totalAmountSplitted})
      split(recipientConditions, Contract.balance)
      Chain.event(PaymentReceivedAndSplitted(Call.caller, Call.value, Contract.balance))

   // STATEFUL FUNCTIONS

   stateful entrypoint transferOwnership(newOwner': address) =
      onlyOwner()
      put(state{owner = newOwner'})

   stateful entrypoint updateAddress(oldAddress': address, newAddress': address) =
      onlyOwnerOrRecipient(oldAddress')
      let weight: int = state.recipientConditions[oldAddress']
      put(state{recipientConditions @ rc = Map.delete(oldAddress', rc)}) // remove old address
      put(state{recipientConditions[newAddress'] = weight}) // add new address
      Chain.event(AddressUpdated(oldAddress', newAddress'))

   stateful entrypoint updateRecipientConditions(recipients': map(address, int)) =
      onlyOwner()
      Chain.event(UpdatingAllRecipients)
      require(sumWeights(recipients') == 100, "sum of weights needs to be 100")
      put(state{recipientConditions = recipients'})
      fireRecipientAddedEvents(Map.to_list(state.recipientConditions))

   // PRIVATE FUNCTIONS

   function onlyOwner() =
      require(Call.caller == state.owner, "caller must be the owner")

   function onlyOwnerOrRecipient(recipient': address) =
      require(Call.caller == state.owner || Call.caller == recipient', "caller must be the owner or the recipient")

   function sumWeights(recipients': map(address, int)) : int =
      let recipientList: list(address * int) = Map.to_list(recipients')
      let intList: list(int) = map(pair_second, recipientList)
      sum(intList, (x) => x)

   function fireRecipientAddedEvents(recipientConditions': list(address * int)) =
      switch(recipientConditions')
         [] => ()
         (recipient, weight) :: l' =>
            Chain.event(RecipientAdded(recipient, weight))

   stateful function split(recipientConditions': list(address * int), totalValue: int) =
      switch(recipientConditions')
         [] => ()
         (recipient, weight) :: l' =>
            Chain.spend(recipient, totalValue / 100 * weight)
            split(l', totalValue)

   // GENERIC HELPER FUNCTIONS

   function map(f : 'a => 'b, l : list('a)) : list('b) =
      switch(l)
         [] => []
         e :: l' => f(e) :: map(f, l')

   function foldr(f : (('a, 'b) => 'b), z: 'b, l : list('a)) : 'b =
      switch(l)
         [] => z
         e :: l' => f(e, foldr(f, z, l'))

   function sum(l : list('a), f : 'a => int) : int =
      foldr((x, y) => x + y, 0, map(f, l))

   function pair_second(tuple) =
      switch(tuple)
         (_, e) => e
```

**Comment by velzevur** [comment]
How do you use the endpoint? Dry run accepts a mixed list of transactions and `call_req`-s. Do you provide a transactions or rather you're simply providing `call_req`-s? If you provide `call_req`-s, please bear in mind that you _should_ provide a [gas limit](https://github.com/aeternity/aeternity/blob/master/apps/aehttp/priv/oas3.yaml#L3148). Note that it is not a mandatory field so you _could_ as well not provide it. Not providing it of course makes it impossible for the node to limit a computationally heavy call. That's why a node plays it safe and if the `gas` is not provided in a `cal_req` - it uses a default maximum dummy value of 1 000 000 gas.

So if you're providing 6+ `call_req`-s in a single dry-run without `gas` - it could easily go beyond the 6 million limit.

Regarding how the gas limit is being computed: the `tx` comes with a fee. In order for the node to make an educated guess how many transactions can be fit in a micro block - there is a gas representation for a transaction's computations. For example a spend transaction is worth 15 000 gas. More info [here](https://github.com/aeternity/aeternity/blob/master/apps/aecore/src/aec_governance.erl#L106-L165). Then size is taken into account (as it also comes with a gas representation). If the transaction includes a contract call, the gas limit provided for the call is also included in the mix. This is how the node checks if a transaction _could_ fit in a micro block. This is being reused in this endpoint as well :)

**Comment by marc0olo** [comment]
ok that's interesting. thanks for that detailed explanation.

so currently I am testing the endpoint by providing an encoded transaction (`tx`) in the `DryRunInputItem` instead of the `DryRunCallReq` object (`call_req`). the encoded transaction includes the property `gas` < 6 000 000 and I am always getting `Over the gas limit`. as I am only providing 1 transaction that shouldn't be a problem.

but even if the default maximum dummy value of 1 000 000 gas is being used I am wondering why I am getting that issue if this transaction is using a lot less gas. might the problem be that I provided > 1 000 000 gas in the encoded transaction?

I am using protocol version 5 (Iris)

**Comment by velzevur** [comment]
> but even if the default maximum dummy value of 1 000 000 gas is being used I am wondering why I am getting that issue if this transaction is using a lot less gas. might the problem be that I provided > 1 000 000 gas in the encoded transaction?

Dummy value is only for `call_req`-s that do not provide a gas limit. Encoded transactions do come with gas limit.

Can you provide me with a cURL that reproduces the issue?

**Comment by marc0olo** [comment]
@velzevur short update here:
1. the encoded tx mentioned above I am only using for `ContractCreateTx` in the `DryRunInputItem` because the `call_req` objects seem to require the contract property
1. for all other dry-runs I am using the `call_req` objects

this is an example body (copied from java debugger) which I provide to the external dry-run endpoint where I always get `Over the gas limit`. (default node-config for external dry-run)

```
class DryRunInput {
    top: null
    accounts: [class DryRunAccount {
        pubKey: ak_twR4h7dEcUtc2iSEDv8kB7UFJJDGiEDQCXr85C3fYF8FdVdyo
        amount: 0
    }]
    txs: [class DryRunInputItem {
        tx: null
        callReq: class DryRunCallReq {
            calldata: cb_KxH1rqnZP3nRsyw=
            contract: ct_Fj76mCvmf4XgrU48AmYwVTCRbK2wrXtL49yE1QUHfXzcPtLRB
            amount: 1000000000000000000
            gas: 1579000
            caller: ak_twR4h7dEcUtc2iSEDv8kB7UFJJDGiEDQCXr85C3fYF8FdVdyo
            nonce: 3
            abiVersion: 3
            context: null
        }
    }]
    txEvents: false
}
```

**Comment by marc0olo** [comment]
@velzevur so I am pretty sure about the problem now:
- when providing more than 1 000 000 gas in a `call_req` the dry-run doesn't work

for the `ContractCreateTx` which I need to provide as encoded transaction due to the required `contract` attribute in the `DryRunCallReq` object the dry-run also fails when providing 1 000 000 or a bit less gas. when I provide 800 000 gas it works and when I provide 900 000 gas or more I get `Over the gas limit`

**Comment by marc0olo** [comment]
ok another addition to that -> it seems like the default limit of the node is 1 000 000 gas instead of 6 000 000 gas which is obviously causing the problem that the dry-runs for contract calls fail.

for the contract creation the limit always needs to be set a certain amount lower than the gas limit for whatever reason

**Comment by velzevur** [comment]
>  it seems like the default limit of the node is 1 000 000 gas instead of 6 000 000 gas 
You are right. We have a tiered system for defaults: the most important one is in (the schema](https://github.com/aeternity/aeternity/blob/master/apps/aeutils/priv/aeternity_config_schema.json#L313) (1mln) and if not provided in the schema - we have a backup value in (the code](https://github.com/aeternity/aeternity/blob/master/apps/aehttp/src/aehttp_dispatch_ext.erl#L41) (6mln). I will provide a fix in the schema so the default is indeed 6mln gas

> for the contract creation the limit always needs to be set a certain amount lower than the gas limit for whatever reason

Around 45 000 gas are reserved for the computation of the create transaction itself (and a bit more of the computations of the size).
