### ISSUE TITLE
HTTP endpoint: get next nonce

### ISSUE THREAD

**Issue by velzevur** [aeternity/aeternity#3662]
Sending transactions for the same account from a distributed system requires knowledge for the latest account `nonce`. Since transactions can be included, rejected or even replaced by transactions with a competing nonce, the only source of truth shall be either a wallet or a synced node.

Provide an endpoint that returns what the next nonce for an account would be, taken into consideration transactions in the pool, originating from the same account.

**Comment by marc0olo** [comment]
I always thought about a tx-manager on client side that handles nonce-management. this is definitely an interesting solution.
