### ISSUE TITLE
AENS: delegated revocation fails if owner has zero balance with `bad_signature`

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeternity#3674]
While playing around with the delegation signatures I experienced a strange behavior.

I performed following AENS actions:
- pre-claim
- claim
- extend
- transfer (=> new owner with zero balance)
- revoke
    - **fails** for the new owner if he has zero balance with `bad_signature`
    - **succeeds** for the new owner if I prefund the account prior to the contract call

Note:
- this might also be the case for other actions like `AENS.transfer` (haven't checked that)

**Comment by hanssv** [comment]
The delegation signature check looks up the account (to check that it isn't a generalized account) - for non-existing accounts it should conclude it is a "normal" account rather than error out with a `bad_signature`. 

Consensus breaking to fix.
