### ISSUE TITLE
oracle response missmatch using delegation

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeternity#3696]
## Intro
I experienced some strange behavior and need to clarify what's going on here. it seems like providing a certain string as response via delegated signature using a smart contract returns a different value than returning exactly the same string using a regular `OracleRespondTx`.

I am using the following contract to provide a delegated oracle response:
```sophia
@compiler >= 6

contract OracleDelegation =

    stateful payable entrypoint register_oracle(acct : address,
                                                sign : signature,
                                                qfee : int,
                                                ttl  : Chain.ttl) : oracle(string, string) =
        Oracle.register(acct, qfee, ttl, signature = sign)

    stateful payable entrypoint extend_oracle(o   : oracle(string, string),
                                             sign : signature,
                                             ttl  : Chain.ttl) =
        Oracle.extend(o, signature = sign, ttl)

    payable stateful entrypoint create_query(o    : oracle(string, string),
                                             q    : string,
                                             qttl : Chain.ttl,
                                             rttl : Chain.ttl) : oracle_query(string, string) =
        require(Oracle.check(o), "oracle not valid")
        require(Call.value =< Oracle.query_fee(o), "insufficient value for qfee")
        Oracle.query(o, q, Oracle.query_fee(o), qttl, rttl)

    stateful entrypoint respond(o    : oracle(string, string),
                                q    : oracle_query(string, string),
                                sign : signature,
                                r    : string) =
        Oracle.respond(o, q, signature = sign, r)

    entrypoint query_fee(o : oracle(string, string)) : int =
        Oracle.query_fee(o)
```

the string I am returning as value is `sunny =)`

## Actual behavior
The oracle response for `sunny =)` using `OracleRespondTx` is `or_c3VubnkgPSkesJvd` which equals `sunny =)` when decoding it.

The oracle response for `sunny =)` using the `respond` entrypoint with a delegated signature is `or_IXN1bm55ID0pxKdUsg==` which equals `!sunny =)` (which is definitely wrong).
- Here I am not 100% sure if this is a problem in the decoding logic of our SDK. But I guess and hope this is not the case 😅 

## Expected behavior
The response is the same in both variants.

**Comment by marc0olo** [comment]
so it turns out this is depending on the ABI version of the oracle. so we need to differentiate the way how to decode the response

how is the javascript sdk handling this currently? @davidyuk @mradkov

**Comment by hanssv** [comment]
From a node perspective everything is working as intended.
