### ISSUE TITLE
Tx gas used being used for validations

### ISSUE THREAD

**Issue by velzevur** [aeternity/aeternity#3706]
The transaction gas is a measure of how much computations are required to apply a transaction. A transaction comes with a gas limit. This is the upper boundary of how much gas it can use. The actual gas used is known only after the transaction had been applied.

Currently when validating incoming blocks the gas limit is being used. This means that if a transaction has a big limit but it actually consumes significantly less gas - then the actual computations in the block are less and there is "space" for more transactions. In order this to happen when validating an incoming transaction the actual gas used shall be used instead. This might be a separate mapping in the transaction's list between tx hash and actual gas used.

**Comment by marc0olo** [comment]
according to @thepiwo this only requires a softfork 🤔

**Comment by thepiwo** [comment]
@marc0olo I was wrong, of course thats a hard fork

**Comment by marc0olo** [comment]
thanks for clarifying :-)
