### ISSUE TITLE
 Missing CORS headers for errors on /v3/names endpoint

### ISSUE THREAD

**Issue by kenodressel** [aeternity/aeternity#3732]
A followup to #3192 . There are still endpoints that return no CORS headers on errors. The example I stumbled upon is this: 

https://mainnet.aeternity.io/v3/names/%21.chain

I already checked with @dincho and it seems to be an issue with the node itself, not the infrastructure setup.

**Comment by velzevur** [comment]
Some more debugging:
```
$ curl -H "Origin: http://example.com" -i https://mainnet.aeternity.io/v3/names/nemame.chain                                                                                                                                                       [15:00:35]
HTTP/2 404 
content-type: application/json
content-length: 27
date: Fri, 26 Nov 2021 13:01:12 GMT
access-control-allow-credentials: true
access-control-allow-methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
access-control-allow-origin: http://example.com
access-control-max-age: 1800
server: Cowboy
vary: origin
x-cache: Error from cloudfront
via: 1.1 c114c55bb579a01518cf64c447d45272.cloudfront.net (CloudFront)
x-amz-cf-pop: DUS51-P1
x-amz-cf-id: UwKuI4w_nw1765DHk_JCVfamD3ZGoyM_WLiwUiFJ7DhDr9zBQ-HM9g==

{"reason":"Name not found"}%   ```

So for _some_ names - there is a correctly set CORS. While for others:
```
$ curl -H "Origin: http://example.com" -i https://mainnet.aeternity.io/v3/names/%21.chain                                                                                                                                                          [15:01:12]
HTTP/2 500 
content-length: 0
date: Fri, 26 Nov 2021 13:01:54 GMT
x-cache: Error from cloudfront
via: 1.1 2c4f54cad5da50a372b086710d5ffc62.cloudfront.net (CloudFront)
x-amz-cf-pop: DUS51-P1
x-amz-cf-id: MVUVJB3BnaSzrz8Rwdh6pRZAI15RFw2c699d9S6VolAgQ_nzVybbBg==```

Note that in the second case the node does not return code 404 (as in - _name not found_) but rather crashes with 500. The logs point to bug in IDNA integration. This means - there are 2 bugs:
1. CORS not set for error 500
2. The API shall not crash on special names
