### ISSUE TITLE
include `out of gas` error in `getTransactionInfoByHash` response

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeternity#3775]
The node doesn't seem to provide that info, `getTransactionInfoByHash` returns object like:
```json
{
  "callerId": "ak_2WV5aAk3SCpVzm13q6mvvybbKaLj1YYyjFB93AEvWvNXxKLg5w",
  "callerNonce": 5,
  "contractId": "ct_55eqP7c5CKiVBfGPoqssa5xYpvdtp7uWLgCHirqhNNvMavZyH",
  "gasPrice": 1000000000,
  "gasUsed": 10,
  "height": 764,
  "log": [],
  "returnType": "error",
  "returnValue": "cb_Xfbg4g=="
}
```
`cb_Xfbg4g==` using compiler decodes to
```json
{
  "error": [
    ""
  ]
}
```
We can assume that a call run out of gas if `gasUsed` is equal to gas limit. Also, we can call txDryRun for the same tx:
```json
{
  "callerId": "ak_2Q5WkttXYzLBtt7sBivaRWUabBNc1niHKoYtB7m6vgkgfJMmVs",
  "callerNonce": 5,
  "contractId": "ct_q5R3jcSimsztC7pvJvXNEHm5qemsUFZhE53TydEaSM9sfRiCd",
  "gasPrice": 1000000000,
  "gasUsed": 10,
  "height": 1128,
  "log": [],
  "returnType": "error",
  "returnValue": "cb_T3V0IG9mIGdhc4mjSdQ="
}
```
`cb_T3V0IG9mIGdhc4mjSdQ=` using compiler decodes to
```json
{
  "error": [
    "Out of gas"
  ]
}
```
The best to solve it I think to make the node report "Out of gas" in on-chain call

_Originally posted by @davidyuk in https://github.com/aeternity/aepp-sdk-js/issues/1309#issuecomment-965729976_

**Comment by marc0olo** [comment]
would that info easily accessible from the node after the tx has been included in the node or would it be an effort to collect and provide this?

if it's easily doable we should get that info from this endpoint.

**Comment by hanssv** [comment]
It would be an effort to collect and provide this (the node would basically have to dry-run it).

The reason that the error is always `""` on-chain is that we don't want to put error messages under consensus - therefore, the error message is zeroed out before we write it to the chain.

**Comment by hanssv** [comment]
> cb_T3V0IG9mIGdhc4mjSdQ= using compiler decodes to

You still don't have a base64check-decoder in JS?

**Comment by marc0olo** [comment]
thanks for the quick answer. what do you think about letting our SDK assume the `out of gas` error if `gasUsed` equals `gas` (limit) and the `returnType` is `error`?

**Comment by marc0olo** [comment]
> You still don't have a base64check-decoder in JS?

mhhh, actually I think we should have 😱  @davidyuk can you comment this?

**Comment by davidyuk** [comment]
I propose to do a dry-run by sdk to get an error message if the on-chain call was rejected with the empty error.

> You still don't have a base64check-decoder in JS?

Promising to try to do it using calldata library a bit later

**Comment by marc0olo** [comment]
> I propose to do a dry-run by sdk to get an error message if the on-chain call was rejected with the empty error.

sounds reasonable. but we should perform the dry-run at the same height like the tx was performed IMO. otherwise there could be a different result, right?

> Promising to try to do it using calldata library a bit later

mhhh but this is nothing FATE specific? so we currently still use http compiler for decoding base64check? we should definitely open an issue in the SDK then

**Comment by marc0olo** [comment]
I think if we go the dry-run route we don't really need this feature - at least it's nothing with priority. maybe we can leave it open as it would save us one additional API call in case of an error.

**Comment by hanssv** [comment]
Just a thought, perhaps you should do it the other way around, _first_ dry-run it, and only if it is successful you should actually post it 🤔

**Comment by marc0olo** [comment]
> Just a thought, perhaps you should do it the other way around, _first_ dry-run it, and only if it is successful you should actually post it 🤔

I think that should be up to the developer to decide. we actually have a living closely related issue for automatic gas consumption estimation here: https://github.com/aeternity/aepp-sdk-js/issues/1286

in this specific case here it's really about getting specific info about a transaction after broadcasting it and in case of an error get at least he `out_of_gas` error displayed

**Comment by hanssv** [comment]
Makes sense. If you dry-run the transaction, you can get the other error reasons also, but out_of_gas is perhaps the most common one.

**Comment by marc0olo** [comment]
🤔 maybe we should combine automatic gas consumption and error detection. probably the dev wants to have both.

**Comment by marc0olo** [comment]
at the moment we don't need this anymore. in case there is demand we can re-open
