### ISSUE TITLE
Can't use GetOracleQueriesByPubkey with `from` option, because the list of queries seems unordered

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#3805]
## Expected Behavior

GetOracleQueriesByPubkey should return the list of queries ordered by the order of mining (or the nonce order if all queries were made by a single account). Also, it should have the same order internally to make `from` option work properly.

## Actual Behavior

GetOracleQueriesByPubkey returns the list of queries in random(?) order.

## Steps to Reproduce the Problem

1. Execute `npm i @aeternity/aepp-sdk@10.0.0 -g`
1. Run the reproduction script
1. Ensure that the GetOracleQueriesByPubkey output is not ordered by nonce

or

1. Clone https://github.com/aeternity/aepp-sdk-js
1. Checkout to `v10.0.0` tag
1. Do `npm i`
1. Create the reproduction script
1. Switch `isTestnet` to `false`
1. Execute `docker-compose up`
1. Run the reproduction script
1. Ensure that the GetOracleQueriesByPubkey output is not ordered by nonce

Reproduction script
```js
const { Node, Universal, MemoryAccount, Crypto } = require('@aeternity/aepp-sdk'); // or './dist/aepp-sdk' in SDK repo

const isTestnet = true
const url = isTestnet ? 'https://testnet.aeternity.io' : 'http://localhost:3013'
const genesis = {
  publicKey: 'ak_2dATVcZ9KJU5a8hdsVtTv21pYiGWiPbmVcU1Pz72FFqpk9pSRR',
  secretKey: 'bf66e1c256931870908a649572ed0257876bb84e3cdf71efb12f56c7335fad54d5cf08400e988222f26eb4b02c8f89077457467211a6e6d955edb70749c6a33b'
};

(async () => {
  console.log('url', url)
  const sdk = await Universal({
    nodes: [{ name: 'testnet', instance: await Node({ url }) }],
    compilerUrl: 'https://compiler.aepps.com',
    accounts: [MemoryAccount({ keypair: Crypto.generateKeyPair() })]
  })

  await sdk.spend(1e15, await sdk.address(), { onAccount: genesis })
  const oracle = await sdk.registerOracle('input', 'output')
  const queryIds = []
  let oracleQueries
  for (let i = 0; i < 5; i++) {
    const message = `query: #${i}`
    const { id } = await oracle.postQuery(message)
    console.log('\ncreated', message, id)
    queryIds.push(id)

    oracleQueries = (
      await sdk.api.getOracleQueriesByPubkey(oracle.id)
    ).oracleQueries
    console.log('oracleQueries.length', oracleQueries.length)
    oracleQueries.forEach(({ id, senderNonce }) => console.log('query', id, 'none:', senderNonce))
  }

  const idx = Math.floor(Math.random() * queryIds.length)
  console.log(`\nqueryIds[${idx}]`, queryIds[idx])
  oracleQueries = (
    await sdk.api.getOracleQueriesByPubkey(oracle.id, { from: queryIds[idx] })
  ).oracleQueries
  console.log('oracleQueries.length', oracleQueries.length)
  oracleQueries.forEach(({ id, senderNonce }) => console.log('query', id, 'none:', senderNonce))
})()
```

## Configuration, logs, error output, etc.

The configuration of the local node see in `docker-compose.yml`.

Reproduction output:
```
$ node ./test.js
url https://testnet.aeternity.io

created query: #0 oq_2FrNWC12yJENSjQ1Z2UQBnaGrY5FhN8rDtzSpX1Sx2Ruz9gjCy
oracleQueries.length 1
query oq_2FrNWC12yJENSjQ1Z2UQBnaGrY5FhN8rDtzSpX1Sx2Ruz9gjCy none: 2

created query: #1 oq_c8CuDB64qvqVRqU3MSbHVtxnkzfQ7PoCB5yAZoXSMZGeEC6dA
oracleQueries.length 2
query oq_c8CuDB64qvqVRqU3MSbHVtxnkzfQ7PoCB5yAZoXSMZGeEC6dA none: 3 // should be the last
query oq_2FrNWC12yJENSjQ1Z2UQBnaGrY5FhN8rDtzSpX1Sx2Ruz9gjCy none: 2

created query: #2 oq_2Ki7M92H9QFzTLzpJTSjJhH99gf4QfMR5wjLESfcbaqGJA8zFZ
oracleQueries.length 3
query oq_c8CuDB64qvqVRqU3MSbHVtxnkzfQ7PoCB5yAZoXSMZGeEC6dA none: 3
query oq_2FrNWC12yJENSjQ1Z2UQBnaGrY5FhN8rDtzSpX1Sx2Ruz9gjCy none: 2
query oq_2Ki7M92H9QFzTLzpJTSjJhH99gf4QfMR5wjLESfcbaqGJA8zFZ none: 4 // query inserted in the right position

created query: #3 oq_2pUfJz7J2BWUPzUtuc9MY4frmt4rahfUg9yMLwEYpdnPf3rr32
oracleQueries.length 4
query oq_c8CuDB64qvqVRqU3MSbHVtxnkzfQ7PoCB5yAZoXSMZGeEC6dA none: 3
query oq_2FrNWC12yJENSjQ1Z2UQBnaGrY5FhN8rDtzSpX1Sx2Ruz9gjCy none: 2
query oq_2Ki7M92H9QFzTLzpJTSjJhH99gf4QfMR5wjLESfcbaqGJA8zFZ none: 4
query oq_2pUfJz7J2BWUPzUtuc9MY4frmt4rahfUg9yMLwEYpdnPf3rr32 none: 5 // query inserted in the right position

created query: #4 oq_R8uKWb2Dbw1BhJArjBxxR7NUzW6L2pYAmFG5LeFscVgPeSNDB
oracleQueries.length 5
query oq_R8uKWb2Dbw1BhJArjBxxR7NUzW6L2pYAmFG5LeFscVgPeSNDB none: 6 // should be the last
query oq_c8CuDB64qvqVRqU3MSbHVtxnkzfQ7PoCB5yAZoXSMZGeEC6dA none: 3
query oq_2FrNWC12yJENSjQ1Z2UQBnaGrY5FhN8rDtzSpX1Sx2Ruz9gjCy none: 2
query oq_2Ki7M92H9QFzTLzpJTSjJhH99gf4QfMR5wjLESfcbaqGJA8zFZ none: 4
query oq_2pUfJz7J2BWUPzUtuc9MY4frmt4rahfUg9yMLwEYpdnPf3rr32 none: 5

queryIds[1] oq_c8CuDB64qvqVRqU3MSbHVtxnkzfQ7PoCB5yAZoXSMZGeEC6dA
oracleQueries.length 3
query oq_2FrNWC12yJENSjQ1Z2UQBnaGrY5FhN8rDtzSpX1Sx2Ruz9gjCy none: 2
query oq_2Ki7M92H9QFzTLzpJTSjJhH99gf4QfMR5wjLESfcbaqGJA8zFZ none: 4
query oq_2pUfJz7J2BWUPzUtuc9MY4frmt4rahfUg9yMLwEYpdnPf3rr32 none: 5
// oq_R8uKWb2Dbw1BhJArjBxxR7NUzW6L2pYAmFG5LeFscVgPeSNDB is missed in this list
// but it was created later than oq_c8CuDB64qvqVRqU3MSbHVtxnkzfQ7PoCB5yAZoXSMZGeEC6dA
```

## Specifications

  - Virtualization: container
  - Node Version: v6.3.0

**Comment by hanssv** [comment]
```
$ npm i @aeternity/aepp-sdk@10.0.0 -g
zsh: command not found: npm
```
Nope, still doesn't seem to work...

On a serious note, I think the real question is why would you expect the queries to be sorted by *nonce*? And what would that even mean, the queries can be posted by different senders so nonces will not mean much?

If I remember correctly the queries are sorted by query id and you can use pagination if you want to control how many results you want 🤔

**Comment by davidyuk** [comment]
> Nope, still doesn't seem to work

Is there a better tool to create reproductions? I know reproductions based on js sdk may be difficult to analyze because of possible problems on its side.

> why would you expect the queries to be sorted by nonce?

Actually, to be sorted as they mined. This should be the same as nonce order when all queries are created by the same account as in my reproduction. This order in combination with `from` would allow getting queries mined after the last received instead of diffing all received queries with all queries known by node (as js sdk does now) to get new queries.

I thought `from` is exactly for this purpose, but if it is just for pagination of existing queries would be nice to document the ordering somewhere (e.g. swagger file) if it is not documented already. Or we can change queries order to allow an additional use case of `from`.

**Comment by hanssv** [comment]
Sorry, missed the notification on this thread... 

They are sorted, lexicographically on the queryId. `from` is for pagination. There is no obvious sorting, _order they were mined_ doesn't really mean much, and since there is nothing in the oracle query object that indicate the order it isn't really feasible 🤔
