### ISSUE TITLE
Update S3 credentials

### ISSUE THREAD

**Issue by zxq9** [aeternity/aeternity#3816]
The "Upload artifacts to S3" task is failing in CI; apparently it is time to update the `envdir /secrets`.
Example: https://app.circleci.com/pipelines/github/aeternity/aeternity/9780/workflows/a89c1489-a03b-4e49-a95c-d55b4042677d/jobs/180442
```#!/bin/bash -eo pipefail
envdir /secrets aws s3 sync --acl public-read /tmp/packages s3://aeternity-node-builds/

envdir '/secrets' does not exist

Exited with code exit status 111

CircleCI received exit code 111
```

**Comment by michalbagrowski** [comment]
fixed: https://app.circleci.com/pipelines/github/aeternity/aeternity/9783/workflows/1f887af7-6e5a-49c1-bf71-15a18169a489/jobs/181225
