### ISSUE TITLE
Support of docker buildx and multi-plaforms

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#3846]
relates to https://github.com/aeternity/aeternity/pull/3845 and https://github.com/aeternity/aeternity/issues/3799

- build/check jobs should run on single platform to save runtime
- master should be build both for amd64 and arm64
- releases should be build both for amd64 and arm64

**Comment by thepiwo** [comment]
@dincho we also need to build aesophia_http images with buildx for arm64

**Comment by marc0olo** [comment]
@dincho it would be cool if we could prioritize this issue. it's important for making a public announcement of the new aeproject version :-)

really looking forward to see this. thanks @thepiwo!

**Comment by dincho** [comment]
Guys, this is the node repo after all, please file a ticket in https://github.com/aeternity/aesophia_http

**Comment by marc0olo** [comment]
done

**Comment by dincho** [comment]
Unfortunately rocksdb won't build on arm64 with gcc 9.4.0 which is what's shipped in 20.04 focal. That's fine for now we still ship with 18.04 but it could be troublesome in future.

rel: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100985

**Comment by dincho** [comment]
done in https://github.com/aeternity/aeternity/pull/4026
