### ISSUE TITLE
Logging Level 'none' does not prevent writing log files to disk

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#3863]
```
11:36:32.040 [error] Failed to open log file /usr/local/Cellar/aeternity-node/6.4.0/log/aeternity.log with error not owner
11:36:32.042 [error] Failed to open log file /usr/local/Cellar/aeternity-node/6.4.0/log/aeternity_mining.log with error not owner
11:36:32.044 [error] Failed to open log file /usr/local/Cellar/aeternity-node/6.4.0/log/aeternity_metrics.log with error not owner
11:36:32.045 [error] Failed to open log file /usr/local/Cellar/aeternity-node/6.4.0/log/aeternity_pow_cuckoo.log with error not owner
11:36:32.047 [error] Failed to open log file /usr/local/Cellar/aeternity-node/6.4.0/log/aeternity_sync.log with error not owner
11:36:32.049 [error] Failed to open log file /usr/local/Cellar/aeternity-node/6.4.0/log/aestratum.log with error not owner
11:36:32.109 [info] Setup running ...
11:36:32.111 [info] Directories verified. Res = ok
11:36:32.111 [info] Setup phase [normal] 100
11:36:32.111 [info] Searching for config file aeternity.{json,yaml} in directory /private/tmp/aeternity-node-test-20220228-98150-8a3dxy/.aeternity/aeternity
11:36:32.111 [info] Searching for config file aeternity.{json,yaml} in directory /usr/local/Cellar/aeternity-node/6.4.0
11:36:32.111 [info] Searching for config file epoch.{json,yaml} in directory /private/tmp/aeternity-node-test-20220228-98150-8a3dxy/.epoch/epoch
11:36:32.112 [info] Searching for config file epoch.{json,yaml} in directory /usr/local/Cellar/aeternity-node/6.4.0
11:36:32.112 [info] No config file specified; using default settings
11:36:32.112 [info] aeu_env:read_config()-> ok
11:36:32.112 [info] Setup phase [normal] 101
11:36:32.126 [info] OS env config: [{"AE__CHAIN__DB_PATH",[<<"chain">>,<<"db_path">>],"/private/tmp/aeternity-node-test-20220228-98150-8a3dxy/data"},{"AE__CHAIN__PERSIST",[<<"chain">>,<<"persist">>],"false"},{"AE__KEYS__DIR",[<<"keys">>,<<"dir">>],"/private/tmp/aeternity-node-test-20220228-98150-8a3dxy/keys"},{"AE__LOGGING__LEVEL",[<<"logging">>,<<"level">>],"none"}]
11:36:32.126 [info] Map fr OS env config: #{<<"chain">> => #{<<"db_path">> => <<"/private/tmp/aeternity-node-test-20220228-98150-8a3dxy/data">>,<<"persist">> => false},<<"keys">> => #{<<"dir">> => <<"/private/tmp/aeternity-node-test-20220228-98150-8a3dxy/keys">>},<<"logging">> => #{<<"level">> => <<"none">>}}
11:36:32.126 [info] validation: update_config, result: [{ok,#{<<"chain">> => #{<<"db_path">> => <<"/private/tmp/aeternity-node-test-20220228-98150-8a3dxy/data">>,<<"persist">> => false},<<"keys">> => #{<<"dir">> => <<"/private/tmp/aeternity-node-test-20220228-98150-8a3dxy/keys">>},<<"logging">> => #{<<"level">> => <<"none">>}}}]
11:36:32.126 [info] aeu_env:apply_os_env()-> #{<<"chain">> => #{<<"db_path">> => <<"/private/tmp/aeternity-node-test-20220228-98150-8a3dxy/data">>,<<"persist">> => false},<<"keys">> => #{<<"dir">> => <<"/private/tmp/aeternity-node-test-20220228-98150-8a3dxy/keys">>},<<"logging">> => #{<<"level">> => <<"none">>}}
```

As it's seen in the logs `AE__LOGGING__LEVEL` is set to `none` but the node tries writing to the wrong location and it fails for permissions issue.

related to #3861 and #3860

**Comment by richcarl** [comment]
Is that output from a Mac OS image? The paths refer to `/usr/local/Cellar/...` which I assume only would exist on a Mac using Homebrew. Anyhow, the configuration is clearly wrong in this case (but since the ticket is old, it might have been fixed since then) - the log directory should be set to $HOME/aeternity/node/log. Did the Mac OS installer/setup/whatever somehow set HOME to be the install dir? I'm not going to look further at the Mac OS specific details unless someone really wants me to.

However, also in a normal Ubuntu-based image (e.g. `aeternity-v6.9.0-macos-x86_64`), we get the same kind of crash if we launch with a different user than 1000 or root, as in `docker run -it --user 1337 aeternity/aeternity` (see #4228), because the log directory /home/aeternity/node/log does not exist yet (and would only be writeable by user 1000 anyway).

**Comment by dincho** [comment]
Yes, the log output seems from an macos package, the main issue question is why log level set to `none` does not work as expected and not produce any logs (tries to write somewhere).

**Comment by richcarl** [comment]
To achieve this, it looks like the logger has to be started later than the setup phase in the node bootup sequence, so the configuration gets read before the node decides to start logging. Or start the logger first but logging to stdout until configuration is read, and then switch the logging to disk if specified.

**Comment by dincho** [comment]
Yes, it sounds a bit like chicken and egg in the first proposal, as where the configuration errors goes to? The second proposal looks more workable

**Comment by richcarl** [comment]
Closing this because Lager simply has no concept of disabling file creation depending on the log level. See #4228 for making it possible to run in a read-only environment. Trying to do this via log level is not the right approach.
