### ISSUE TITLE
Allow contracts to be called by name

### ISSUE THREAD

**Issue by hanssv** [aeternity/aeternity#4009]
Currently names can resolve to Oracles and Accounts at the protocol level (in transactions) - it would make perfect sense to also allow  names to resolve to Contracts. This would apply to ContractCallTx.

**Comment by hanssv** [comment]
Note: This was not my idea, I'm merely noting it down here to keep a consistent record of possible CERES additions.

It sound seemingly simple, but I wonder if the call state tree, etc. might make this hard or even unfeasible...

**Comment by marc0olo** [comment]
did that come from @thepiwo ? :) I remember him talking about that in the past

**Comment by thepiwo** [comment]
didn't come from me :D

**Comment by thepiwo** [comment]
🚀
