### ISSUE TITLE
Sync speed status

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#4072]
## Is your feature request related to a problem? Please describe.

- Compare sync speed of multiple machines/setups/configurations i.e. machine 1 vs machine 2 comparison.
- Estimate time for 100% sync completion.

## Describe the solution you'd like

Show estimated sync speed and estimated completion time in node status cmd/API endpoint.
The most reasonable metric to me is blocks per second. That's of course is estimated metric based on last X blocks.

Given that metric it could show an estimated time to complete (100% sync as well), given it already shows sync %.

A metric would be very helpful as well.

## Describe alternatives you've considered

I don't see any other reasonable alternative other than metering a given period of time and manual recording of numbers and calculations.

## Additional context

None

**Comment by hanssv** [comment]
During sync we already log things like:
```
2024-01-18 09:17:34.886 [info] <0.2097.0>@aec_sync:post_blocks:{951,5} Synced blocks 889343 - 889344   (2 generations (104.70 ms/gen), 37 mblock(s), 41 tx(s))
```

Collecting that data (this doesn't need to be super robust/persistent, so a process is good enough?!) and serving it - either through `/status` or a separate `/sync-status` endpoint - should be straightforward.
