### ISSUE TITLE
allow an AENS delegate signature to handle all names owned by account

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeternity#4080]
I am planning to request a grant to develop an application that allows to wrap multiple AENS names into an NFT (AEX-141). in order for a contract to easily transfer ownership of user-owned AENS names to the NFT contract such signature would help a lot.

it would be awesome if this could be handled by just requiring one specific delegate signature of the user-account instead of having to provide dedicated delegate signatures for each name individually.

I have already shortly discussed this topic with @hanssv and it seems like it shouldn't be a big deal to include this in the upcoming Ceres hardfork.

**Comment by marc0olo** [comment]
@davidyuk you haven't prepared this in develop branch of SDK already, right? should be complete on node side. why do you assume it is not complete? 🤔

**Comment by davidyuk** [comment]
I mean to close this issue as it looks implemented on the node side. I think I can't keep SDK compatible with Ceres because of https://github.com/aeternity/aepp-calldata-js/issues/210

**Comment by marc0olo** [comment]
I assume it is kept open until Ceres is released (and activated) 😅
