### ISSUE TITLE
Queries beyond GC point fail with "Internal server error" rather than a notice about GC

### ISSUE THREAD

**Issue by zxq9** [aeternity/aeternity#4096]
## Expected Behavior
When a query is sent to a GC'd node over the JSON API endpoint (for example, "/v2/accounts/[AccID]/height/[BlockHeight]") if the object does appear on chain but the requested block height is unavailable due to GC the response should be something along the lines of "GC: Out of range" to inform the user that the data exists, but only a full node can service the query.

## Actual Behavior
When a query is sent to a GC'd node over the JSON API endpoint if the object does appear on chain but the requested block height is unavailable due to GC the response that is returned is "Internal server error". This is wrong, of course -- the server is experiencing no error, it is functioning correctly as a GC'd node.

An example of covering for the current behavior is the current way the Vanillae Erlang lib handles this case:
https://github.com/aeternity/Vanillae/blob/36ddcfc97f4d884106dc644e36f0977c4e064c0a/bindings/erlang/src/vanillae.erl#L491-L497

**Comment by uwiger** [comment]
Fixed in #4119. Closing
