### ISSUE TITLE
Name not found

### ISSUE THREAD

**Issue by jyeshe** [aeternity/aeternity#4112]
## Expected Behavior
Request to https://testnet.aeternity.io/v3/names/s0m3l0ngn4m3.chain or 
https://testnet.aeternity.io/v3/names/s0m3l0ngn4m3 would return the name.

## Actual Behavior
404 Not Found while the Mdw displays it: https://testnet.aeternity.io/mdw/v2/names/s0m3l0ngn4m3.chain

## Node status
```
{"difficulty":58443428,"genesis_key_block_hash":"kh_wUCideEB8aDtUaiHCtKcfywU6oHZW6gnyci8Mw6S1RSTCnCRu","listening":true,"network_id":"ae_uat","node_revision":"a42c1b1e84dabdad350005213a2a9334113a6832","node_version":"6.8.1","peer_connections":{"inbound":14,"outbound":10},"peer_count":93,"peer_pubkey":"pp_rFy9TFrXAZnJh6WNC3KnCSmu2o1vCoXi5Ty78bBa6NjFwdqte","pending_transactions_count":1,"protocols":[{"effective_at_height":425900,"version":5},{"effective_at_height":154300,"version":4},{"effective_at_height":82900,"version":3},{"effective_at_height":40900,"version":2},{"effective_at_height":0,"version":1}],"solutions":0,"sync_progress":100.0,"syncing":false,"top_block_height":747616,"top_key_block_hash":"kh_9LadGb4eQR9k63tjgL1xKjpGiJBFq8BQJxqSnuVWCDY8DcGH2"}
```

## Specifications
  - Node Version:  "6.8.1"

**Comment by jyeshe** [comment]
Reproduced with https://testnet.aeternity.io/v3/names/nameupdt8001.chain (both cases an update was interrupted after waiting some minutes).

**Comment by hanssv** [comment]
Both queries work now (and the MDW does not 😅 ), is there some caching or other HTTP trickery in between?

**Comment by jyeshe** [comment]
> Both queries work now (and the MDW does not sweat_smile ), is there some caching or other HTTP trickery in between?

It's good on the Mdw too (:
https://testnet.aeternity.io/mdw/v2/names/nameupdt8001.chain 

Got it using the SDK on a retry of name update with higher fee in order to get it minted faster. But I can't reproduce it now. The update is pretty fast and validates duplicate tx by nonce on multiple retries. 

Please feel free to close it Hans.
