### ISSUE TITLE
Expose name auction details maintained by the node

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4128]
To handle name auctions correctly, node has to know
- the block height at wich auction ends
- the maxumim bid
- the account that made that bid

Currently, if I request details for a name at the auction I would get a 404 error (`GetNameEntryByName`). Would be nice to have an endpoint providing the above details.

**Comment by hanssv** [comment]
Looks like a reasonable feature request to me. Though adding it to the OpenSwaggerSomething will probably be painful 😅
