### ISSUE TITLE
Transactions that use hash signatures fail when the blockchain is empty

### ISSUE THREAD

**Issue by mitchelli** [aeternity/aeternity#4148]
## Expected Behavior
The transaction to succeed.
...

## Actual Behavior
The transaction fails with a signature_check_failed error.
...

## Steps to Reproduce the Problem

  1. remove files from the mnesia data directory
  2. set autostart: false in the aeternity.yaml
  1. make a make request using the Javascript API
  1. ...

## Configuration, logs, error output, etc.

- `aeternity.yaml` configuration file
---
peers:
    - aenode://pp_HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X@node1:3015
    - aenode://pp_Dxq41rJN33j26MLqryvh7AnhuZywefWKEPBiiYu2Da2vDWLBq@node3:3015

http:
    external:
        port: 3013
    internal:
        port: 3113
        listen_address: 0.0.0.0
        debug_endpoints: true
    cors:
        allow_domains: [""]

websocket:
    channel:
        port: 3014
        listen_address: 0.0.0.0

keys:
    peer_password: "top secret"
    dir: ./keys

chain:
    persist: true

mining:
    beneficiary: "ak_twR4h7dEcUtc2iSEDv8kB7UFJJDGiEDQCXr85C3fYF8FdVdyo"
    beneficiary_reward_delay: 2
    autostart: false
    cuckoo:
        edge_bits: 15
        miners:
            - executable: mean15-generic

fork_management:
    network_id: devnet

```
---
REPLACEME
some_config:
```

- `log/aeternity.log` 
- 
localnet-node1-1  | 11:57:58.216 [info] Failed signature check on tx: {error,signature_check_failed}, <<98,242,240,216,162,192,122,135,211,50,30,222,45,106,245,50,229,152,12,247,243,213,16,189,150,201,104,16,195,0,185,70>>

## Specifications

  - Node Version: 6.9.0

**Comment by hanssv** [comment]
Signing the hash of the transaction was introduced in Fortuna(?) hard-fork - my guess is that the first generation here is an earlier protocol version. Can't remember what the default is - but you've got an empty `fork_management:`
