### ISSUE TITLE
Timeout on dev mode keyblock emitter too limiting

### ISSUE THREAD

**Issue by uwiger** [aeternity/aeternity#4163]
## Expected Behavior

When running devmode, it should be possible to emit any number of key blocks.

## Actual Behavior

Requests time out for larger numbers. It's a gen_server call, using the default 5-second timeout.

## Steps to Reproduce the Problem

  1. Activate dev mode, e.g. `AE__SYSTEM__DEV_MODE=true bin/aeternity console`
  1. request keyblocks using `aedevmode_emitter:emit_keyblocks(5000)`
  1. (request will likely time out, as emission takes ca 2.5 secs/1k

Suggest setting the timeout on this particular request to `infinity`.

**Comment by uwiger** [comment]
See issue aeternity/aeplugin_dev_mode#24

**Comment by marc0olo** [comment]
@uwiger I think we can close this, thanks! :)
