### ISSUE TITLE
`ttl` is missed in transaction details

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4168]
## Is your feature request related to a problem? Please describe.

We were comparing fee calculation between sdk and an other service and found out that we can't get TTL for the already mined transaction by its hash. It was needed because the `ttl` value can change transaction size and hence the fee.

## Describe the solution you'd like

https://testnet.aeternity.io/v2/transactions/th_2YVQL8NE34fYMvP6UUMW2tSYEGPrg57ag2AvdkFzaVGVVsn7au should include `ttl` value.

**Comment by mitchelli** [comment]
The ttl is not set if the original request didn't have a ttl:


aecli account spend my-ae-wallet2 ak_XwTENL7b2UNqrbqqput7GrPPBxbXXWx7kiwxCz2C4oMAp1H8u 16660000000001 

aecli inspect th_77nRxv3sZ5cxL7qGtmrVtvC9ouZmXrQ1ZzSJLop9HGmq3YLCs
Tx hash _________________________________ th_77nRxv3sZ5cxL7qGtmrVtvC9ouZmXrQ1ZzSJLop9HGmq3YLCs
Block hash ______________________________ mh_2HXswwBHhTyGfv3VX2RLSFwPkEn7VyREN5rj8QErixmN4wBZj9
Block height ____________________________ 1221
Signatures ______________________________ ["sg_7kz28gYJW8o47yD7PtUyHRJPg5oa2rG7m61drxkWGGkwS9hwTvgbdXfWhU54RTdtr3NmwjKQ9ummbjPPWrCKLw3R8WjPX"]
Tx Type _________________________________ SpendTx
Sender account __________________________ ak_2B2wt3V8R92NKXRVT9ovbrT7kdSzhBBCsfVQf3PSfsCuL4JcgK
Recipient account _______________________ ak_XwTENL7b2UNqrbqqput7GrPPBxbXXWx7kiwxCz2C4oMAp1H8u
Amount __________________________________ 16660000000001
Payload _________________________________ ba_Xfbg4g==
Fee _____________________________________ 16780000000000
Nonce ___________________________________ 24
**TTL _____________________________________ N/A**
Version _________________________________ 1


If the ttl is set in the transaction it is returned


aecli account spend -T 101225 my-ae-wallet2 ak_XwTENL7b2UNqrbqqput7GrPPBxbXXWx7kiwxCz2C4oMAp1H8u 1666000000099

aecli inspect th_9CMpdwZtWcTCpKDAmxVNM429S24FbrXvRbXGcvi8dospGKLzK
Tx hash _________________________________ th_9CMpdwZtWcTCpKDAmxVNM429S24FbrXvRbXGcvi8dospGKLzK
Block hash ______________________________ mh_2HXswwBHhTyGfv3VX2RLSFwPkEn7VyREN5rj8QErixmN4wBZj9
Block height ____________________________ 1221
Signatures ______________________________ ["sg_5ihk57s6ovrhh5ZoinBtoQKBLmfFWKFdGDEv2zEMKQ1AXX8SQHiiA3awjowbKs3RQ9PzYRKVKRJkqoWZGfLnaYm2C9Vb4"]
Tx Type _________________________________ SpendTx
Sender account __________________________ ak_2B2wt3V8R92NKXRVT9ovbrT7kdSzhBBCsfVQf3PSfsCuL4JcgK
Recipient account _______________________ ak_XwTENL7b2UNqrbqqput7GrPPBxbXXWx7kiwxCz2C4oMAp1H8u
Amount __________________________________ 1666000000099
Payload _________________________________ ba_Xfbg4g==
Fee _____________________________________ 16860000000000
Nonce ___________________________________ 27
**TTL _____________________________________ 1012251220**
Version _________________________________ 1

**Comment by hanssv** [comment]
No, a TTL is not set in the response if:
 1. the original TTL didn't have a TTL, _or_
 2. if the original TTL was set to 0

**Comment by davidyuk** [comment]
Didn't know that it works this way, thank you!

with ttl https://testnet.aeternity.io/v2/transactions/th_2BqCRVj3Ti1puZLkpSAD2wpHw2Za43mXWzH5TNW5vPcuaM73ZN 
without ttl https://testnet.aeternity.io/v2/transactions/th_zwcRRc4SUGFnQk1pc1nmy84h513XbP6k4aSBqAaxwMWnEdLuJ
