### ISSUE TITLE
provide API to return account balance only & return 0 for non-existing accounts

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeternity#4187]
related to https://github.com/aeternity/superhero-wallet/issues/2239

a client would typically want to fetch a balance for a specific account and does not care whether the account actually exists or not. if the account not exists, there should just be "0" returned.

@brainiacfive please add some comment or correct me here if needed

**Comment by hanssv** [comment]
For reference see #1352

**Comment by marc0olo** [comment]
thanks for providing the reference @hanssv 

keep in mind that I am playing proxy for @brainiacfive here.

maybe it should be added as a convenience function to the SDK @davidyuk ? 🤔 personally I don't have a strong opinion, but it feels kind of stupid having to deal with 404 error on client side just to check for the correct balance and setting it to zero in case the account does not exist

**Comment by davidyuk** [comment]
> maybe it should be added as a convenience function

It is already there 😃
https://github.com/aeternity/aepp-sdk-js/blob/5df22dd297abebc0607710793a7234e6761570d4/src/chain.ts#L272-L275
if you call `AeSdk:getBalance` with an address of non-existing account it would return 0. The only thing is that you still see the error message in Chrome console with default settings https://stackoverflow.com/a/30847631 🤷‍♀️

**Comment by hanssv** [comment]
Sounds like we have the bases covered in SDK 👍
