### ISSUE TITLE
Ceres (v6) gas consumption much higher than on Iris (v5)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeternity#4197]
## Expected Behavior
There shouldn't be any difference in gas consumption when executing the same entrypoints on the exact same contract which has previously been deployed on Iris (v5).

## Actual Behavior
Apparently the gas consumption on Ceres is ~3x higher than on Iris for the following contract:
- https://github.com/marc0olo/aens-nfts/blob/ceres-playground/development/smart-contracts/contracts/AENSWrapping.aes

### Iris (v5)
```sh
Gas used (unwrap_all for 3 names): 52494
        ✔ unwrap_all (1443ms)
```

### Ceres (v6)
```sh
Gas used (unwrap_all for 3 names): 172494
        ✔ unwrap_all (1467ms)
```

## Steps to Reproduce the Problem

Execute tests in [ceres-playground](https://github.com/marc0olo/aens-nfts/blob/ceres-playground) and [iris-only-gas-consumption](https://github.com/marc0olo/aens-nfts/blob/iris-only-gas-consumption).

To execute the tests, following commands need to be executed in the folder `development/smart-contracts`:

```sh
docker-compose up -d
npm i
npm run test:iris
```

Note:
- Node needs to be installed
- For comparison it is sufficient to execute the tests with a smaller set of AENS names. Those can be outcommented in the array starting in line 25 of the iris test file.

**Comment by marc0olo** [comment]
reason for the change:
- https://github.com/aeternity/aeternity/pull/3828

**Comment by hanssv** [comment]
So this is as indicated by the above it is intentional - reading values from the state is underpriced currently - and contract calls that update a lot of state (like updating 100 names in an NFT!) will be more expensive. Exactly how much more expensive is still up for discussion!
