### ISSUE TITLE
Allow configuration of genesis contracts file

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#4221]
## Expected Behavior

```
chain:
  genesis_contracts_file: /path/to/contracts.json # should work with both absolute and relative path to the package root
```

## Actual Behavior

Create a file named `{networkId}_contracts.json` in the release data dir, which is different in various setups.

Setup of hyperchains requires contracts initialization. This is done via contracts.json configuration.

**Comment by uwiger** [comment]
PR #4200  is intended to provide support for this

**Comment by dincho** [comment]
done in #4200
