### ISSUE TITLE
Allow configuration of genesis accounts in the config

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#4222]
For custom test (or not) networks it would be much easier to boostrap with few lines in the configuration file instead of external files, FS mappings and deployments. Further more in 21 century it would allow accounts configuration via environment variables.

## Expected Behavior

```
chain:
  genesis_accounts:
    ak_11111111111111111111111111111115rHyByZ: 10000000
```

## Actual Behavior

Only allowed through additional file.

**Comment by uwiger** [comment]
PR #4200 is intended to provide support for this

**Comment by dincho** [comment]
I don't think so, it's about file locations, this issue is about inline aeternity.yaml configuration.
