### ISSUE TITLE
Allow running in read-only environment

### ISSUE THREAD

**Issue by dincho** [aeternity/aeternity#4228]
The title should says it all, but:

```docker run -it --user 1337 aeternity/aeternity```

depends on #3860

**Comment by richcarl** [comment]
Why would this be expected to work? The dockerfile sets up everything under `/home/aeternity/node` and creates user `aeternity` with UID 1000. Running with another UID (except root) will not have write permissions under `/home/aeternity`.

**Comment by dincho** [comment]
This ticket is more or less for me too keep investigating why it could not run it with other users (given they have rx permissions). The node should not write to the file system unless instructed to do so (i.e. log paths etc.).

I guess this ticket could be renamed to "allow running in read-only environment".

**Comment by richcarl** [comment]
Ok, that makes more sense. Is the node expected to be able to run without writing to the data directories at all?

**Comment by dincho** [comment]
Yes, that would be my expectation, we already have a configuration option to disable database persistence which works as expected so far.

I can't think of any other module that needs to write to the FS

**Comment by hanssv** [comment]
Starting the node without any config will default to logging being on though, right?

To achieve this you need to (either statically or programatically) modify `lager` application configuration (originating from the `sys.config` I belive). As soon as lager starts it checks its `lager_file_backend` files for writeability - regardless of log-level. Not sure how feasible that is, but I haven't looked at it in detail...

**Comment by hanssv** [comment]
#4077 is the same thing?

**Comment by richcarl** [comment]
Note: when launching in the background (with the 'start' or 'daemon' flags), this is done via the `run_erl` shim, which disconnects stdin and attaches stdout and stderr to disk files named erlang.log.{1, ...}. These files cannot be turned off. To run without write permissions, the system needs to be launched in the foreground, with the 'console' or 'foreground' flags.

**Comment by richcarl** [comment]
Closing this. Will be fixed by #3860
