### ISSUE TITLE
Make AENSv2.preclaim optional

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4247]
It consistency with https://github.com/aeternity/aeternity/issues/4174

Currently, if I'm skipping preclaim step in AENS delegation signature, I'm getting `Error in aens_claim: name_not_preclaimed` while calling AENSv2.claim on Ceres protocol.

cc: @hanssv

**Comment by hanssv** [comment]
I'm pretty sure I've tested that - you do set `salt` to `0`, right?

I'll add an explicit test for this...

**Comment by davidyuk** [comment]
> you do set salt to 0, right?

Nope! I've ensured that it works on sdk side in https://github.com/aeternity/aepp-sdk-js/pull/1932
