### ISSUE TITLE
Make equivalent of debug tx in mempool for external api

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4283]
Initially, it was implemented in https://github.com/aeternity/aeternity/pull/3671, only as debug, internal endpoint.
Exposing it as external would allow getting tx status on gateways if debug endpoints are not enabled, like on mainnet.aeternity.io.

Also, in js-sdk, I want to provide detailed error messages (not only "tx didn't get mined in n blocks"), but I dropped support of the internal node's api some time ago, and don't want to bring it back only because of this feature 🤪

As I understand nodes already calculating this information while maintaining the mempool, so it doesn't look expensive to expose it in external api.

**Comment by davidyuk** [comment]
Consider adding this data to GetTransactionByHash endpoint to poll this data at once 🤔

**Comment by dincho** [comment]
There is a reason this to be exposed as internal endpoint as it runs the VM.

**Comment by davidyuk** [comment]
As I understand ProtectedDryRunTxs also runs the VM, but it is already exposed.

**Comment by hanssv** [comment]
Isn't this just a two step process: grab the transaction + do a dry-run?

**Comment by davidyuk** [comment]
Dry-run looks to be a working solution, the only problems I see are:
- if we find that tx stuck in mempool, call dry-run, and the tx gets included in between we will get `tx_nonce_already_used_for_account` error
- not all transaction types supported by dry-run:
> Supports all TXs except GAMetaTx, PayingForTx and OffchainTx

**Comment by hanssv** [comment]
_If_ the tx gets included right in between you'll still be happy I guess... You could build some logic around `tx_nonce_already_used_for_account` to be extra safe, but this would probably be rare...

But the second point is valid (though I doubt there is more than 100 Txs of those kinds during the last _year_)... What about just extending the dry-run API to allow dry-running something that is in the mempool 🤔
