### ISSUE TITLE
Provide extra info along "Invalid tx" error

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4284]
Related issue https://github.com/aeternity/aeternity/issues/4283.

Currently, if for some reason I posted (to `/transactions`) an invalid transaction I'm getting `{"reason":"Invalid tx"}`. Various mistakes end up with this message, like:
- invalid signature,
- low nonce,
- low ttl,
- low fee.

Would be good if the node provide some key to indicate exactly the first check failed, like in `debug/check-tx/pool`. This would allow tools (like js-sdk) to provide developers with more friendly error messages, to simplify debugging in some cases.

As far as these checks are already done by the node while accepting transaction, it shouldn't require extra computations to provide it in response.

**Comment by hanssv** [comment]
Here are the possible errors - you'll get the error_code (the snake cased first word below) in a new field in the Error object:

- already_known : Tx is already in mempool (or GC:ed).
- already_accepted : Tx is already on chain.
- invalid_at_protocol : Tx is not valid (incorrect parameters) in the current protocol.
- signature_check_failed : The TX signature is not valid.
- too_much_gas_for_auth_function : Too much gas is provided for the GA authenticate function (GAMetaTx).
- generalized_account_cant_sign_non_meta_tx : (One of) The signing account(s) is a generalized account and should use a GAMetaTx as authentication.
- nonce_too_low : The nonce is too low.
- nonce_too_high : The nonce is too high.
- too_low_fee : The fee is too low.
- too_low_gas_price : The gas price is too low.
- too_low_gas_price_for_miner : This node does not accept this gas price, it is too low.
- ttl_expired : The TX TTL has expired.
