### ISSUE TITLE
Reject spend tx immediately if the recipient contract is not payable

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4310]
I've sent a spend tx to a contract, but it is stuck in mempool. I've checked the reason and got this message:
```json
// 20240318141332
// https://testnet.aeternity.io/v3/debug/check-tx/pool/th_anEmjaiVMYGCHSDEPmaLpUxmyFKp17yAu6sMiYAYLMwJw4uWG
{
  "status": "account_is_not_payable"
}
```
I don't think the unpayable contract can become payable so we can reject such SpendTx on transaction posting.

That tx details:
```json
    {
      "block_hash": "none",
      "block_height": -1,
      "hash": "th_anEmjaiVMYGCHSDEPmaLpUxmyFKp17yAu6sMiYAYLMwJw4uWG",
      "signatures": [
        "sg_aLduYjGDLuKDygRqg1fYiWNe4vuQ6uCqVgZTb2gz41MSd6p8WsX4G7DW9XNBSXhDpZPQw1AKvBBhTTX8zqVxkyeGBJFbr"
      ],
      "tx": {
        "amount": 1,
        "fee": 16760000000000,
        "nonce": 1178,
        "payload": "ba_Xfbg4g==",
        "recipient_id": "ak_1EJ9hBo5RJBaQxWT1RkvBFw4VaAfHfKvDRK1ioXpqSjx2xmKq",
        "sender_id": "ak_21A27UVVt3hDkBE5J7rhhqnH5YNb4Y1dqo4PnSybrH85pnWo7E",
        "ttl": 922010,
        "type": "SpendTx",
        "version": 1
      }
    },
```

**Comment by davidyuk** [comment]
Isn't it costly to keep such transaction in mempool?

> Maybe some of the tools along the way could warn that spending to this account is perhaps not a great idea

Checking this on sdk side also would be an additional cost. Even more expensive because of extra http requests.

**Comment by dincho** [comment]
Is there a hypotheses when an account can _become_ payable ?  🤔

**Comment by hanssv** [comment]
@dincho An address/account is by default payable (i.e. any account that isn't in the state tree (yet) is considered payable). When a contract is created, the associated account is set to either payable or not payable depending on the contract (default is _not_ payable). After the contract creation there is no way to change the payable status.

@davidyuk in this case the cost for checking is small enough that I think we can add it as the default - doing HTTP is as you suggest worse 😅 - though the client could cache this... 

Let's add it to the mempool-checks!

**Comment by dincho** [comment]
> After the contract creation there is no way to change the payable status.

That was my mine question, and by account, I meant contract account/address.
