### ISSUE TITLE
Don't encode binary pointer key as string in name details

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4317]
Together with mdw team we find out that an aens pointer key can be arbitrary bytes. But in name details it is encoded as string that doesn't works well if we are have raw bytes in key.

Example name update transaction: tx_+M4LAfhCuEDC0qgighRqQfsb7+rBdj3YgPQrn6eJlFg/JeSUGaHT0Ib1llr/D/EChZmpwH+APTgGSMlKVnABGZNkOKCNo8gCuIb4hCIBoQFx4GF37I8Up2XTBXfJoSVMFRTdDlJMSpnDZpC7Qr0M4QahAgfcQ3oAn1mHbkr0vac5wk5YqlaW8mSDRFGoGMJaW6Z1gwK/IO3sid6tvu9teUtleaEBK4KUmZC+wTFE6qE33lHiP5x0TC8fqd/kWaeSpvwKVYaCDhCGEBRyHqAAHpZnprU=

Example of name details output:
```
$ curl http://localhost:3013/v3/names/pdy67dxykdsrETvH6YIcGkvCNPHFTY.chain | jq .
{
  "id": "nm_4TnSeXE5LJ25t4qsqjBkSrY2tTpHVQGdiVU9NPtK2NeFU8yj6",
  "owner": "ak_s9pgJcAAiWBfpuV6pF9QnxEZBVfe9537t3bTxphrDFaV3LVBq",
  "pointers": [
    {
      "id": "ak_LAQanhrS2ZzL5nGyh5UZuZb5RvWNuggmQNM7vWq2kCPxDNdvi",
      "key": "ޭ��myKey"
    }
  ],
  "ttl": 180027
}
```

Node details:
```
$ curl http://localhost:3013/v3/status | jq .
{
  "network_id": "ae_dev",
  "node_revision": "b0a7140abdb6b6df79ebbb2a8b75e6397cbb6eae",
  "node_version": "6.12.0+52.b0a7140ab",
  "protocols": [
    {
      "effective_at_height": 1,
      "version": 6
    },
    {
      "effective_at_height": 0,
      "version": 1
    }
  ]
}
```

**Comment by davidyuk** [comment]
Consider encoding keys in the pointers object as base64 to be consistent with the mdw implementation https://github.com/aeternity/ae_mdw/issues/1665

**Comment by hanssv** [comment]
As discussed elsewhere - changing this is trivial, and makes sense - question is how much of a breaking change is it?

**Comment by hanssv** [comment]
A less breaking solution would perhaps be to _add_ a field with the the encoded key?

**Comment by dincho** [comment]
I don't think it should be base64 but more like bytearray encoded?

**Comment by hanssv** [comment]
Well, bytearray is base64 (+ check bytes) - but sure `ba_...` (or `cb_...`) could be used in this case, I agree!

**Comment by dincho** [comment]
I don't know what initial idea behind cb_, but it feels like it's abused nowadays or it's name is wrong :)
