### ISSUE TITLE
Typo in `fiat_converstion_url` parameter

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aeternity#4335]
https://github.com/aeternity/aeternity/blob/69569d248869191046c02a370bd75f6427558a29/apps/aeutils/priv/aeternity_config_schema.json#L1647-L1650

https://github.com/aeternity/aeternity/blob/69569d248869191046c02a370bd75f6427558a29/apps/aehttp/priv/oas3.yaml#L2732

As I understand it should be `fiat_conversion_url`, I would sent a PR, but is it a breaking change now?

**Comment by dincho** [comment]
Let's do that before 7.0.0
