### ISSUE TITLE
Fix sync of node when too far behind

### ISSUE THREAD

**Issue by happi** [aeternity/aeternity#4373]

**Comment by happi** [comment]
Fix sync of a Hyperchain node when too far behind

**Comment by hanssv** [comment]
The problem, if I remember correctly, is that the synchronization between fetching blocks from the parent, and fetching blocks from another HC node is off. This results in a situation where sync gets stuck saying _parent chain block not available_.

I guess the best way forward is to try to re-create this situation in a test and then fix it...
