### ISSUE TITLE
Detect crashes in log file when running tests

### ISSUE THREAD

**Issue by ThomasArts** [aeternity/aeternity#4436]
We found a real error by inspecting the log of a intermitting test case. Turns out that this crash happens more often, but can be happily accepted.

There is some existing code to scan log files for errors and crash reports. Use that in the hyperchain test suites

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
