### ISSUE TITLE
Make HCElection contract aware of last leader in epoch

### ISSUE THREAD

**Issue by ThomasArts** [aeternity/aeternity#4448]
We plan to have a contract call on chain in which the PIN proof is stored.
This call should only update the contract state if it is the last leader that calls the contract.

(We don't want others to be able to manipulate the proof provided).

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
