### ISSUE TITLE
Timestamp the initial hyperchain block

### ISSUE THREAD

**Issue by richcarl** [aeternity/aeternity#4449]
Subtask of #4375

- Calculate the timeslot for a block at a specific height.
- Timestamp first real block.
- Set T0 to timestamp-max_block_timestamp.
- Function for calculating min and max timestamp for block (N).

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by richcarl** [comment]
Done in #4487
