### ISSUE TITLE
Micro block logic is unaware of current leader

### ISSUE THREAD

**Issue by ThomasArts** [aeternity/aeternity#4453]
By moving the micro blocks before key blocks we introduced the situation in which the contract state(s) in the micro block are not updated with the current leader. As a consequence, contract calls that depend on the current leader do not work (see PR #4451).

It would be beneficial to actually have the contract state updated before the creation of the first (and only) micro block in a generation. This would require a change to the `conductor` using a `pre_transform_micro_block` or similar.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
