### ISSUE TITLE
Remove old PoS from code base

### ISSUE THREAD

**Issue by ThomasArts** [aeternity/aeternity#4455]
We seem to have no use of other proof-of-stake implementations and the maintenance burden to update that code with the speed of developing hyperchains makes it a burden.

Remove all PoS related code that does not contribute to hyperchain development.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
