### ISSUE TITLE
Implement Pinning Rewards

### ISSUE THREAD

**Issue by klercker** [aeternity/aeternity#4469]
New design for carry over is:
1. Epoch_info state gets new fields 
a.  `base_pin_reward` **integer**, which has the currently agreed pin reward (can be changed in vote - in the _future_...), this is set for the. next epoch in `step_eoe()`. Initialized from config
b. `carry_over_pin_reward` **integer**. Initialized to `0`.
2. A (calculated) `epoch_pin_reward` field is added to `epoch_info()` return value (or possibly as it's own function). Value is `base_pin_reward + carry_over_pin_reward`.
3. `step_eoe()` is extended with two arguments
a. `base_pin_reward` **integer**, new and future (hopefully agreed-on) value for `epoch_info.base_pin_reward`. Per default, consensus will just set this to the previous value, but in the future there might be some kind of voting on how it should be adjusted.
b. `carry_over` **boolean** (if possible, otherwise we will fake one). If `true`, `step_eoe()`code will add `epoch_info.base_pin_reward` (current value, not the one given as argument) to `epoch_info.carry_over_pin_reward`. If `false`, `epoch_info.base_pin_reward` is set to `0`. `false` will be sent when a pin was properly validated, `true`otherwise.
4. As part of last block validation, pin proof is validated. In both cases, base_pin_reward value is carried over from the previous `epoch_info`.
a. pin proof is validated: `epoch_pin_reward` value is fetched from `epoch_info` and rewarded to the last block leader. `step_eoe()` is called with `carry_over = false`.
b. no pin proof, or incorrect pin proof: `step_eoe()` is called with `carry_over = true`

_old version_
Plan for implementing pinning reward:

1. Add consensus config key for `pinning_reward_value`
2. Add election contract state value for `carry_over_reward`, extend `epoch_info` with this value too (extending into the `aec_chain_hc`info too).
3. When no proper pin (which is everything but actually successful validation at this point) perform the following in `step_eoe` contract call (or just provide the value and set them in the contract): 
`carry_over_reward = carry_over_reward + pinning_reward_value`
`else`
`carry_over_reward = 0`
If everyone do what they are supposed to in validation, the block should be properly validated.
4. When reward, reward with `carry_over_reward + pinning_reward_value`

**Comment by klercker** [comment]
Either we simply set the next epoch carry-over in `step_eoe` (calculated according to some logic in `aec_consensus_hc`) or we let the `election`(?) contract calculate it (likely given the current `pinning_reward_value` as a parameter in `step_eoe`). The second alternative would easier enable chain owners to make adjustments to how the reward is calculated (rate of inflation etc). But would be a bit more work and also give people more rope to hang themselves with.

**Comment by klercker** [comment]
This plan is now implemented in branch  
`reward_value_config_and_carry_over`. Will PR as soon as #4441 is merged (branch is based from tip of 4441)

**Comment by ThomasArts** [comment]
Sounds good to me... the only kind of thing that I wonder about is whether or not in the life-time of the chain we want to increase/decrease the pinning reward. The solution chosen here is a fixed reward for the lifetime of the chain.
By not storing the value in the contract, but supply it through consensus, we might be more flexible in the future.

**Comment by klercker** [comment]
So changes in config is not picked up by the Node? Good to know, I thought this was the case (so that if reward was changed in the config, it would get picked up next time you looked it up). But now when I think of it, perhaps that is not such a good idea, from a distribution/staking etc POV.

**Comment by klercker** [comment]
Is there any way to config/default these kinds of values in the contract? I understand the update as you go along, but what about initial values?

**Comment by klercker** [comment]
So, new design for carry over is:
1. Epoch_info state gets new fields 
a.  `base_pin_reward` *integer*, which has the currently agreed pin reward (can be changed in vote - in the _future_...), this is set for the. next epoch in `step_eoe()`. Initialized from config
b. `carry_over_pin_reward` *integer*. Initialized to `0`.
2. A (calculated) `epoch_pin_reward` field is added to `epoch_info()` return value (or possibly as it's own function). Value is `base_pin_reward + carry_over_pin_reward`.
3. `step_eoe()` is extended with two arguments
a. `base_pin_reward` *integer*, new and future (hopefully agreed-on) value for `epoch_info.base_pin_reward`. Per default, consensus will just set this to the previous value, but in the future there might be some kind of voting on how it should be adjusted.
b. `carry_over` *boolean* (if possible, otherwise we will fake one). If `true`, `step_eoe()`code will add `epoch_info.base_pin_reward` (current value, not the one given as argument) to `epoch_info.carry_over_pin_reward`. If `false`, `epoch_info.base_pin_reward` is set to `0`. `false` will be sent when a pin was properly validated, `true`otherwise.
4. As part of last block validation, pin proof is validated. In both cases, base_pin_reward value is carried over from the previous `epoch_info`.
a. pin proof is validated: `epoch_pin_reward` value is fetched from `epoch_info` and rewarded to the last block leader. `step_eoe()` is called with `carry_over = false`.
b. no pin proof, or incorrect pin proof: `step_eoe()` is called with `carry_over = true`

**Comment by klercker** [comment]
Not completely happy that the `epoch_info` in `HCElections.aes` feels more or less run over by pinning stuff, but I guess that's just how it is. I could not figure out how to dynamically add the `cur_pin_reward` to the `epoch_info` return value (it's a record, I know. I was hoping for some map-like semantics, but alas...) and I did not wan't to add more contract calls.
